### ISSUE TITLE
Any way to disable the beeping when closing a door?

### ISSUE THREAD

**Issue by thomasthechan** [hjdhjd/homebridge-myq2#10]
I greatly appreciate your putting this together. Just a question if disabling the beeping when closing a door is possible.

**Comment by russmo** [comment]
Not sure what device you have, but I successfully disabled the speaker on my MyQ wall button unit. Not through software, but by desoldering the piezo buzzer from the board. I also did this on another unit by prying the plastic cover off the speaker unit and ripping out and snipping the small wires inside. Others have poured glue inside the hole on top the speaker and quieted it significantly.  I can confirm that everything else works just fine if you remove the speaker from the circuit board.

**Comment by hjdhjd** [comment]
There isn't a way to control this in the API. Additionally, I believe it's a regulatory requirement in most municipalities to beep when an unattended door is closing. I don't think it's easily disabled. Thanks!

**Comment by thomasthechan** [comment]
Thanks all, that makes sense. When using HomeKit or the MyQ app, closing always beeps.

**Comment by seanism** [comment]
Interestingly when I close using the button it doesn't beep. Only closing via HomeKit or the auto close after a minute.
