### ISSUE TITLE
Does this work with the Home Hub kit from

### ISSUE THREAD

**Issue by sokulski** [hjdhjd/homebridge-myq2#100]

**Comment by sokulski** [comment]
Sorry... Submitted before I had intended to.

I mistakenly bought the wrong kit. The 301 bridge works with Alexa but not HomeKit. Would I be able to use this plugin to send commands to the 301 using my MyQ account?

Do those commands go through the MyQ server before they reach the opener?

**Comment by hjdhjd** [comment]
If you can see it in the myQ app, you can likely use this plugin to control your garage door opener. I'd look at the myQ app on iOS or Android and use that as the starting point . If you can, then I'd configure this plugin with your username and password and look at the logs and see if it gets detected and configured.  Best of luck.
