### ISSUE TITLE
HOOBS shows old version of homebridge-myq2 plugin 

### ISSUE THREAD

**Issue by jlg89** [hjdhjd/homebridge-myq2#103]
This is probably not an issue with the plugin, as GitHub and NPM show the current release, but HOOBS wants the issue reported to the plugin developer.

**Description**
The homebridge-myq2 plugin is currently at 2.1.10 published 4 days ago, but HOOBS plugin search still shows 2.1.9 and the "Update" button does not appear, even after multiple reboots.

**Expected behavoir**
HOOBS should reflect the current release of plugins.

**Comment by hjdhjd** [comment]
You're right about that. There's literally nothing I can do here I'm afraid. :smile:

**Comment by donavanbecker** [comment]
@jlg89, use homebridge instead of HOOBs. You will not have this problem

**Comment by hjdhjd** [comment]
@donavanbecker That is a totally legitimate answer to the question posed. :smile: Wish I'd thought of it.
