### ISSUE TITLE
using gateways

### ISSUE THREAD

**Issue by patricegautier** [hjdhjd/homebridge-myq2#12]
Hi there -

Trying to use the gateways option to filter out some of the openers present in the online account, my home bridge config looks like:

       {
            "platform": "MyQ2",
            "email": "xx",
            "password": "yy",
    	   "gateways": [ 9924957, 1807684652 ]
        }

but all I am able to get is something like:

[1/6/2020, 3:07:32 PM] [MyQ2] Error: Couldn't find a MyQ door device.

When I remove the gateways option, all the openers are correctly added, but I just want to skip some of them.

I tried using their names as well..   Any idea?

**Comment by hjdhjd** [comment]
Are you still having a challenge here?

You can specify a gateway by name or by ID. Do you know your gateway IDs?

Also, you should try specifying the gateways as strings, not integers in your config file. Thanks!

**Comment by patricegautier** [comment]
No longer an issue - I solved this with the 'openers' branch
