### ISSUE TITLE
Notification is sometimes backwards?

### ISSUE THREAD

**Issue by bwoodruff** [hjdhjd/homebridge-myq2#13]
Apologies for not having reliable steps to reproduce. I don't notice this all the time, and I'm not entirely sure under which conditions it occurs. 

The problem is that I just had the door close through a time-based automation, but the HomeKit notification showed "Garage Door was opened." Checking the Home app the door shows as closed. Checking the actual door, it is closed. 

Perhaps this is an issue when triggered to close by an automation? Maybe specifically with time based automations?

**Comment by hjdhjd** [comment]
I've seen quirkiness from time to time in HomeKit automations, but not specific to this (or other) plugins. What's the automation you're specifically trying?

**Comment by bwoodruff** [comment]
@hjdhjd 

In theory it should be a fairly simple automation... it closes the door at a specific time. Unfortunately it is an intermittent problem, as with all of the best software problems.

**Comment by hjdhjd** [comment]
Apologies @bwoodruff - if you can reproduce it in a testable way, happy to look at it. Otherwise I’m going to close this one out. Thanks again.
