### ISSUE TITLE
Error every 30minutes

### ISSUE THREAD

**Issue by wangel** [hjdhjd/homebridge-myq2#14]
It doesn't seem to be causing an issue, but every 30minutes I get this in my log file:

`[MyQ2] Error polling MyQ servers: FetchError: request to https://myqexternal.myqdevice.com/api/v4/UserDeviceDetails/Get failed, reason: getaddrinfo ENOTFOUND myqexternal.myqdevice.com`

It appears that my door and the home app work just fine, it's just something I noticed and am not sure if I really should worry with it.

Thanks,

**Comment by shafnitz** [comment]
So this does seem to affect things, at least in my experience. The plugin polls the MyQ servers about every 15 seconds. Once it encounters the error, it no longer attempts to poll the servers, until the Home app is opened again by the user. The result is, if you're using Siri to open your garage, for example, Siri will timeout in attempting to open the garage. It still does, usually open the garage, but after a several second delay, and after Siri reports that it couldn't open the garage door.

**Comment by hjdhjd** [comment]
Should be fixed in 1.2.19 @wangel and @shafnitz - feel free to test and reopen this if it's still an issue.
