### ISSUE TITLE
Auto Close Garage Door

### ISSUE THREAD

**Issue by jeylites** [hjdhjd/homebridge-myq2#17]
Hi 
Currently, using the plugin it works great, just wondering if the Auto close function works.

 I would like to close the garage door after 20sec. Can this be done on the json config?

**Comment by hjdhjd** [comment]
This can't. You can create an automation to do this though in HomeKit. Take a look at homebridgee-delay-switch - it will allow you to create a timed delay. If you create an automation around garage open and close events, you should be able to get to what you want to do. Thanks!
