### ISSUE TITLE
Error getting MyQ devices: Error processing request (217)

### ISSUE THREAD

**Issue by Glitch482** [hjdhjd/homebridge-myq2#19]
Garage door(s) are no longer responding as of yesterday evening, getting a repeated "Error getting MyQ devices: Error processing request (217)" message in logs. 

Anyone else experiencing similar issues?

**Comment by jerrywmartin** [comment]
I am having the same problem. It quit working yesterday.

**Comment by ronald-mendoza** [comment]
Same/similar issue here as well

**Comment by thorleo** [comment]
Same issue here. No changes were made on my end.

**Comment by therealbrad** [comment]
Same. When it first happened I went to the MyQ page and got a 503 response when trying to list my subscriptions. I see that their site is working today but still getting the 217 error message.

**Comment by dswee999** [comment]
Getting the same message here and made no changes.

**Comment by wangel** [comment]
Same here.  My guess is they've changed something in their protocol / API and broke the plugin. 

Will need to wait for someone to reverse engineer it again I assume.

**Comment by patricegautier** [comment]
for what it's worth, things are still working here.

**Comment by Glitch482** [comment]
Moved to the homebridge-chamberlain plugin in the meantime, working well.

**Comment by byronavory** [comment]
In the notes for homebridge-chamberlain, there appears to certain pieces of the API call that he had to move from v5 to v5.1. I wonder if that has something to do with the recent security changes in the app. Regardless, homebridge-myq2 and homebridge-liftmaster2 appear to be using api v4.

**Comment by thorleo** [comment]
Yup ^^. I ended up moving to homebridge-chamberlain .

**Comment by dinof40** [comment]
Did the move to the other app make any difference? I'm getting a lot of the error, but the door is still working. As far as I can tell they are both using the same API.

> In the notes for homebridge-chamberlain, there appears to certain pieces of the API call that he had to move from v5 to v5.1. I wonder if that has something to do with the recent security changes in the app. Regardless, homebridge-myq2 and homebridge-liftmaster2 appear to be using api v4.

"ApiVersion": "5.1", in MyQ .js file

**Comment by hjdhjd** [comment]
All - I don’t see this issue, and I use this plugin daily. If someone is still seeing this problem, can someone ping me here? Otherwise...when I’ve seen errors like this, it’s typically been due to server issues on Liftmaster / Chamberlain’s side. Let me know.

**Comment by hjdhjd** [comment]
I should also add...I'll be working on updating the MyQ API version to v5+ over the next week or two. There are some substantial changes to the API that need to be resolved.
