### ISSUE TITLE
RFE: Door sensor battery status

### ISSUE THREAD

**Issue by sandeen** [hjdhjd/homebridge-myq2#24]
I see that there is a battery status in the MYQ API:

 ```
       {
          "MyQDeviceTypeAttributeId": 132,
          "Value": "1",
          "UpdatedTime": "1590947380597",
          "IsDeviceProperty": false,
          "AttributeDisplayName": "dpsbatterystate",
          "IsPersistent": false,
          "IsTimeSeries": false,
          "IsGlobal": false,
          "UpdatedDate": "2020-05-31T17:49:40.5966181Z"
        },
```

Does the Homekit accessory support low battery status, and if so can this be added to the plugin?
I tried just hacking in a value:

```
// Method to update door state in HomeKit
MyQ2Platform.prototype.updateDoorStates = function (accessory) {
  accessory.getService(Service.GarageDoorOpener)
    .setCharacteristic(Characteristic.CurrentDoorState, accessory.context.currentState)
    .setCharacteristic(Characteristic.StatusLowBattery, 1);
```
 and battery status is then shown, but I got:

```
HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000041-0000-1000-8000-0026BB765291. Adding anyway.
```
so maybe this isn't supported in HomeKit but I'm not too familiar; not sure if this is a homebridge limitation, a homekit limitation, or ...???   Thanks!

**Comment by sandeen** [comment]
Actually I think the error I mentioned was just due to my hackishness and not setting things up properly in the plugin.

I have a patch for the current release that seems to properly show battery status but I'll keep an eye on your refactoring and see about merging it after you're done.

It's a little hard to test because even my "low" battery, if I remove & replace, looks good again for a while.  :)

**Comment by hjdhjd** [comment]
LOL...feel free to create a PR against what’s there now. The refactor is going to take a bit...I got distracted with a different side project for the last couple of weeks.

Much appreciated @sandeen!

**Comment by sandeen** [comment]
OK I'll clean it up a little and do so, and you should _most_ _definitely_ review it, I'm completely new at homekit. :)

**Comment by hjdhjd** [comment]
We are all new until we are not. :smile:
