### ISSUE TITLE
Does this work with Lockitron Bolt, which now is under MyQ

### ISSUE THREAD

**Issue by robertgranholm** [hjdhjd/homebridge-myq2#31]
MyQ has absorbed a smart lock called Lockitron Bolt, I can control this lock inside the MyQ app, and i am looking to control it in the Home app - does this homebridge plugin enable me to do that?

**Comment by pponce** [comment]
I don't think it currently does because the API's that are used for the garage doors don't seem to expose the locks as devices to be controlled.
i'd love to see support for them if the API's calls used for the bolts can be reverse engineered.

**Comment by hjdhjd** [comment]
While I wish it did...the MyQ API is unpublished and has had to be reverse-engineered. Worse, MyQ gets updated regularly with breaking changes that drive all plugins like this nutty trying to keep up. We all wish they would publish a proper API that we can all use and get on with it. All that said...I don't believe anyone's reverse engineered this sufficiently. It may, or may not work. It really depends on how the API sees it. If the API sees it as just another opener, then yes. You'll have to experiment I'm afraid. After I finish the upcoming refactor, I wouldn't mind revisiting this to see if we can make the support work. Thanks!

**Comment by pponce** [comment]
Thanks for your work on this plugin.
I own 2 lockitron bolts and have each connected to a myq hub.  When looking at the devices returned using 
http://api.myqdevice.com/api/v5.1/Accounts/{{AccountID}}/Devices
I don't see the locks returned as devices to be controlled.
So the app must be using a separate api to control the locks,

**Comment by hjdhjd** [comment]
Yep...unfortunately, that makes it difficult to address for now.
