### ISSUE TITLE
Unexpected number in JSON at position 115

### ISSUE THREAD

**Issue by sebastiangoldstein** [hjdhjd/homebridge-myq2#34]
I was having some naming issues with the Garage Doors so I uninstalled and reinstalled.
Now garage doors won't show up in HomeKit
and I keep getting this error in the Log:
https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 115

**Comment by andrewturko** [comment]
This is very likely a duplicate of #32, of which [this comment](https://github.com/hjdhjd/homebridge-myq2/issues/32#issuecomment-649787215) references a fix for.

**Comment by TheEngineerGuy** [comment]
I have performed now changes for quite a few days, but since this morning I am getting this error as well. Seems to be some change on MyQ service end.

Looking at the previous comment, we possibly need a similar fix on this plugin as well.

**Comment by DMBlakeley** [comment]
See issue #32 which is the same problem. Solution posted in that conversation. I have submitted PR to correct but as I am not owner cannot release.

**Comment by TheEngineerGuy** [comment]
Thanks @DMBlakeley Appreciate it bud.

**Comment by hjdhjd** [comment]
Fixed in the latest update.
