### ISSUE TITLE
issues with Siri Suggestions of MyQ garage doors in CarPlay (wrong or outdated doors)

### ISSUE THREAD

**Issue by sebastiangoldstein** [hjdhjd/homebridge-myq2#37]
Explain the issue occurring:
Hi, I'm a Noob at HOOBS so I understand very little of what I am doing, that said:
I switched over to this Plugin because I was having configuration issues with some of the others.
This issue is not unique to this MyQPlugin but maybe you can explain to me how to fix the problem.

I have two Garage doors hooked up to HomeKit via this plugin. In CarPlay when I am close to my home a garage door shows up on the dashboard (Siri Suggestion) to allow me to open the door.
While for a while it was showing me the correct door (mine), now it shows me my wife's which I have no use as I want to get into my garage. I have no idea how to change this.

What's worse is that since I uninstalled the other MyQ plugin that I was testing and installed this one I re-added the garage doors and changed their names both in the Plug-In and Home Kit. However, the Siri Suggestion garage door is an older name, not even part of my Home Kit setup anymore. So not only does the wrong Garage door show up as a Siri suggestion but it is the wrong version of that door so it reports as "unresponsive."

Expected Result
(Give a description of the expected behavior.)
I would love to be able to specify which garage door Siri suggestions displays on my CarPlay dashboard when I am close to my home. I have no idea if there is an Apple setting for this or a HOOBS plugin setting or an iPhone setting or a Carplay, however, since this is the most likely use case for MyQ in Homekit it would seem that it would be an issue that happens to many people with multiple garage doors.

Info
iOS Version: 13.6
Plugin Version: 1.2.22 published 5/20/2020
HomeBridge Version: HOOBS 3.2.6
Node/Npm Version:

**Comment by DMBlakeley** [comment]
How did you uninstall the previous app? Wonder if you have leftovers from the previous app. HomeKit and I assume CarPlay need unique names for each item.

If you are using config-ui-x you can go to Homebridge setting (3 dots, upper right) and there is an option "Remove Single Cached Accessory". Select this option and make sure that there are not any unrecognized accessories.

**Comment by hjdhjd** [comment]
@sebastiangoldstein Any further updates here, or can we close this issue out? Thanks.
