### ISSUE TITLE
Need API v5 

### ISSUE THREAD

**Issue by gh0sti** [hjdhjd/homebridge-myq2#39]
MyQ updated their api request and api v4 is no longer working.

**Comment by DMBlakeley** [comment]
This plugin seems to be taking a bit different approach to logging into MyQ using the path "https://myqexternal.myqdevice.com/" and a different Application ID than that used by the "Homebridge Chamberlin" plugin. 

The api version in the header is "v5.1" so believe that . If I change the https calls to "v5" rather than "v4" the plug-in fails and the Garage Door is removed from Homebridge. I would suggest no changes at the present as the plug-in does not seem to have an operational issue.

**Comment by jonlehtinen** [comment]
[6/27/2020, 12:27:38 PM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 114
[6/27/2020, 12:28:18 PM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 114
[6/27/2020, 12:28:36 PM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 114

Whatever they did, I get this error in my logs now, and as a side effect all my other homebridge devices now fail in the Home app at the "favorites" screen, but all other devices can report out and be controlled if I drill down into their individually assigned rooms except the myq2 garage door opener.

I've reset my hombridge and re-added all the accessories running through homebidge (two nest thermostats, a roomba, and the myq2 garage door opener) and the issue persists.

**Comment by pponce** [comment]
I'm seeing the same issue and impact to other accessories.

**Comment by DMBlakeley** [comment]
This is not a v5 issue, see issue #32 where I have posted a fix for this error which also impacts other accessories. Have submitted PR but @hjdhjd has not responded as of yet.

**Comment by pponce** [comment]
thanks!
Just updated and all is good again.
npm install -g DMBlakeley/homebridge-myq2

**Comment by jonlehtinen** [comment]
Thank you @DMBlakeley, that did the trick.

**Comment by DMBlakeley** [comment]
Glad this worked. There are a couple of other updates in this archive. Please let me know if you run into any other issues.

**Comment by whreams** [comment]
Just tried this also.  Works here on dedicated Mac-mini. Thanks!

**Comment by hjdhjd** [comment]
I'm going to review this over the weekend as well as the PRs. I've also been looking at v5 support and started refactoring the plugin to support it.
