### ISSUE TITLE
Plugin failing starting 2019-10-18

### ISSUE THREAD

**Issue by mcj** [hjdhjd/homebridge-myq2#4]
```
[10/18/2019, 2:34:32 PM] [MyQ2] Error polling MyQ servers: TypeError: Cannot read property 'length' of undefined                                              
[10/18/2019, 2:34:47 PM] [MyQ2] Error polling MyQ servers: TypeError: Cannot read property 'length' of undefined       
```

**Comment by Judas2016** [comment]
Same here; other MyQ plugins I have tried are also breaking

**Comment by yvaldes022** [comment]
Same error on mine

**Comment by ludgats** [comment]
It seams like everyone using the plugin has the same issue.

**Comment by nixta** [comment]
+1

**Comment by ironScripter** [comment]
Me as well. This is the second plugin to do this.

**Comment by nixta** [comment]
Not so sure. I'm able to get POSTMAN to give me a certificate if I change the `Content-Type` to `application/x-www-form-urlencoded`.

**Comment by nixta** [comment]
The [myq-api](https://github.com/thomasmunduchira/myq-api/) seems to be able to connect fine for me. I wonder if homebridge-myq2 should just leverage that?

**Comment by ironScripter** [comment]
I got this working......
It seems as though the MyQ API no longer likes User-Agent, ApiVersion, or BrandId to be included. When I tested with PostMan the API errors when you add those to the call. So to fix I commented out lines 19-21 from index.js in the main module folder. See my example below.
```
var HEADERS = {
    "Content-Type": "application/json",
    //"User-Agent": "Chamberlain/3.120",
    //"BrandID": "2",
    //"ApiVersion": "4.1",
    "Culture": "en",
    "MyQApplicationID": APP_ID
};
```

The log from homebridge then presented a validation error. I found that there was a nested module, located at ./node_modules/node_fetch/index.js, that was doing validation of the headers. I commented out lines 75-77 of that file. See Example below.
```
//if (!headers.has('user-agent')) {
	//headers.set('user-agent', 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)');
//}
```

This fixed my issue.

Hope this helps

**Comment by novacite** [comment]
Thanks ironScripter!  That works like a charm!

**Comment by vfour** [comment]
Thank you @ironScripter ... works great!

**Comment by dppeak** [comment]
I just changed the User-Agent to "myQ/14041 CFNetwork/1107.1 Darwin/19.0.0" and the ApiVersion to "5.1" and didn't need to make the other changes.

Got the updated details from @dxdc on an [issue thread](https://github.com/luisiam/homebridge-liftmaster2/issues/63#issuecomment-544077034) for homebridge-liftmaster2

**Comment by dxdc** [comment]
@ironScripter @dppeak Wow... nice detective work. Strangely, it seems they were only blocking a *specific* `User-Agent` value (or set of values?)? Perhaps this was to discourage the use of an older iOS app.

Didn't test this myself, but this (also) apparent fix is amusing.

https://github.com/caseywebdev/homebridge-chamberlain/pull/55/commits/a3a33996f9f04220a38aac7fdfdc14dbd48df8d6

**Comment by MAscooby** [comment]
Posted a pull request with UserAgent and ApiVersion values suggested by @dppeak which are working for me.

**Comment by hjdhjd** [comment]
I'll be fixing this shortly...

**Comment by hjdhjd** [comment]
Fixed in 1.1.5.

**Comment by benjackson1111** [comment]
> I just changed the User-Agent to "myQ/14041 CFNetwork/1107.1 Darwin/19.0.0" and the ApiVersion to "5.1" and didn't need to make the other changes.


this is what worked for me, the other solution didn't work. Thank you!

**Comment by hjdhjd** [comment]
@benjackson1111 you can just update to the latest version of this plugin and all fixes are incorporated, plus a couple of others.

**Comment by benjackson1111** [comment]
Cool! Nicely done
