### ISSUE TITLE
Is it normal to see the below?  The timestamps are different and I only have one plugin, one instance and one door...

### ISSUE THREAD

**Issue by whreams** [hjdhjd/homebridge-myq2#43]
Is it normal to see the below?  The timestamps are different and I only have one plugin, one instance and one door...

![image](https://user-images.githubusercontent.com/64332758/86137611-17d57980-bab3-11ea-9c1c-230bf47bc094.png)

_Originally posted by @whreams in https://github.com/hjdhjd/homebridge-myq2/issues/23#issuecomment-651824679_

**Comment by DMBlakeley** [comment]
I have noticed that you get logging each time the Garage Door tile is displayed in HomeKit so I would say normal. Must trigger a poll of the garage door status.

**Comment by hjdhjd** [comment]
It does and it is. Closing...:smile:
