### ISSUE TITLE
Error getting MyQ devices: Unauthorized (216)

### ISSUE THREAD

**Issue by av8ndad** [hjdhjd/homebridge-myq2#45]
Just starting getting this error today: 

Error getting MyQ devices: Unauthorized (216)

**Comment by kbrashears5** [comment]
well whatever you do, don't restart your homebridge instance like I just did - it will remove the device from homekit along with any automations

**Comment by jiggad369** [comment]
getting the same issue.

**Comment by LordZork** [comment]
Same issue...

@kbrashears5 I wish I would have checked here first, before restarting Homebridge (doing so removed the device from HomeKit/Home-app for me too)... *sigh*...

Btw, as someone pointed out in the other (same) issue posted, I am also unable to log into chamberlain.com – it says the username/password I entered was/is incorrect (even know that's not true).

Chamberlain is most likely the problem... they are kind of the worst...

**Comment by Technodad** [comment]
+1 on this problem. I am however able to log in to the MyQ app. I did restart Homebridge; the device appears to still be there.

Also getting `Error getting MyQ devices: undefined` - this is more frequent than the `Unauthorized` message, though I suspect these are related.

**Comment by Vermyndax** [comment]
I am getting the same problems as the others. I have a sneaky suspicion about this, since it works fine in the MyQ app and they sell a $70 bridge for HomeKit compatibility (MYQ-G0303-SP). I removed and reloaded the plugin and that was a death knell. The doors are now gone from my HomeBridge and I can't get them back, since I can't get it to authenticate with MyQ.

**Comment by LordZork** [comment]
@Vermyndax lol, I've had the same sneaky suspicion (https://github.com/hjdhjd/homebridge-myq2/issues/44#issuecomment-652652746).  Hopefully we are wrong, but based on how terrible they are with third-party support and partnerships, etc., it makes you wonder.

**Comment by zirdum** [comment]
This issue occurs every API change FYI... The last change from API 3 to API 4 I believe occurred around October of 2019. So expect this to happen again in 8-12 months time.

**Comment by hjdhjd** [comment]
Alright all, v2.0 of the plugin is out. Hopefully all goes well. :smile:
