### ISSUE TITLE
Starting 7/1/2020 the garage door gives "No Response"

### ISSUE THREAD

**Issue by nvdokh** [hjdhjd/homebridge-myq2#46]
It looks like there has been a change in myQ API preventing the homebridge module from working.

**Comment by a-dows** [comment]
Seconded. I'm getting:

[7/1/2020, 20:57:27] [MyQ2] Error getting MyQ devices: Unauthorized (216)
[7/1/2020, 20:57:33] [MyQ2] Error getting MyQ devices: undefined

repeatedly. Verified that the MyQ app has continued to work.

**Comment by Silmar-99** [comment]
Sounds like #44, $45, #46 are related and the same issue...

**Comment by hjdhjd** [comment]
Update to v2.0. Thanks!
