### ISSUE TITLE
myQ API error while logging in: 404 Not Found

### ISSUE THREAD

**Issue by cryptobrian** [hjdhjd/homebridge-myq2#51]
No garage door is showing up.

I'm getting this in the homebridge logs.
[7/4/2020, 2:06:48 AM] [myQ] Successfully connected to the myQ API.
[7/4/2020, 2:06:48 AM] [myQ] myQ API error while logging in: 404 Not Found
[7/4/2020, 2:07:03 AM] [myQ] myQ API error while logging in: 404 Not Found

This is the config i am using:
{
            "platform": "myQ",
            "email": "XXXXXXX@gmail.com",
            "password": "XXXXXX",
            "verbose": true
        }

**Comment by DNSGeek** [comment]
Yes, I'm getting this too.

**Comment by hjdhjd** [comment]
I'm just impressed someone's trying this at 2AM somewhere. :smile:

Waiting a few minutes and then restarting homebridge. The v5 API is incredibly flakey unfortunately. Once it does connect, and it will over the course of a bit of time (see the README), it should be fine.

**Comment by TheEngineerGuy** [comment]
Same, now I am getting this error as well.
 Logged in but 404.

**Comment by DNSGeek** [comment]
I restarted the home bridge and I'm not getting the 404 any more, but I also do not have a garage door in my HomeKit anymore either. The only message I get from myQ is
```
[7/3/2020, 19:18:04] [myQ] Initializing myQ platform...
```
I don't know what it's doing. I'm not getting any 404's but I have no accessories either.

**Comment by hjdhjd** [comment]
The proverbial "it" is trying to login to the MyQ API to get security credentials, and the API seems to be overwhelmed with the switchover that occurred around 7/1, and my guess is that they're trying to ramp up capacity to catch up.

Either that, or the v5 API is just plain flakey.

I say the former because this API was working quite reliably before 7/1. I've been using it for a couple of weeks.

Just. Be. Patient.

It'll eventually populate.

**Comment by TheEngineerGuy** [comment]
Just wondering, is api v5 available on external.myqdevice.com or connect.myqdevice.com?

**Comment by TheEngineerGuy** [comment]
Ok. 1 hour in, was anyone able to get accessories up?

**Comment by DNSGeek** [comment]
No. I just started getting 404s again. As per @hjdhjd's guidance, I'll leave it overnight and see if things are better tomorrow.

**Comment by hjdhjd** [comment]
@DNSGeek you may want to restart homebridge, just for good measure and go to bed...:smile:

I've gotten reports from others that're up and running. So there's that...

**Comment by TheEngineerGuy** [comment]
@hjdhjd Looking at chamberlain plugin, they don't seem to have these issues with v5. Could we check with them to see how their auth is going so smoothly?

**Comment by hjdhjd** [comment]
@TheEngineerGuy I'll take a look later this weekend. To be clear...I really don't view this as a problem as much as it is an inconvenience until we login. The API's been solid outside of logging in and until the last couple of days, I've had no issues at all logging in.

Yeah...it's super annoying to wait (imagine trying to develop and debug like this!) for the API to let us login, but once it does, it's been good.

**Comment by hjdhjd** [comment]
For what it's worth, I average on taking 5-10 minutes to get logged in, though it's gone the better part of an hour before.

**Comment by TheEngineerGuy** [comment]
I think if it would happen only for the first time, I wouldn't care as much, but on every restart might be bit of a problem as this would create a long delay every time we update UI, HB or kernel, which does tend to happen once every week or so.

Well take a look when you have a chance, might just help us.

**Comment by hjdhjd** [comment]
I think I found it. Sneaky bugger. @TheEngineerGuy going to post an update shortly.

**Comment by TheEngineerGuy** [comment]
kk. I am tuned homeboy. What was it?

**Comment by hjdhjd** [comment]
@TheEngineerGuy update to 5.0.1 and give it a try.

**Comment by TheEngineerGuy** [comment]
Just clicked it.

**Comment by TheEngineerGuy** [comment]
Ok this time the connection was immediate. But still 404.

**Comment by DNSGeek** [comment]
Updated to 5.0.1. Still getting 404's. Looking at the logs, I've been getting non stop 404's for the last 2 hours.

**Comment by hjdhjd** [comment]
@DNSGeek Update to 5.0.2 and share the relevant log portions please if you're still having trouble. Thanks.

**Comment by DNSGeek** [comment]
```
[7/3/2020, 21:56:44] [myQ] Initializing myQ platform...
[7/3/2020, 21:57:11] [myQ] Successfully connected to the myQ API.
[7/3/2020, 21:57:25] [myQ] myQ API error: 404 Not Found
[7/3/2020, 21:57:25] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 21:57:28] [myQ] myQ API error: 404 Not Found
[7/3/2020, 21:57:28] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 21:57:30] [myQ] myQ API error: 404 Not Found
[7/3/2020, 21:57:30] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 21:57:44] [myQ] myQ API error: 404 Not Found
[7/3/2020, 21:57:44] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 21:57:59] [myQ] myQ API error: 404 Not Found
[7/3/2020, 21:57:59] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 21:58:14] [myQ] myQ API error: 404 Not Found
[7/3/2020, 21:58:14] [myQ] myQ API error: unable to refresh. Will retry later.
```

**Comment by hjdhjd** [comment]
Alright. I'm hopeful it's the application identifier that myQ uses that's the issue. Sigh. Can you try out 2.0.3?

**Comment by TheEngineerGuy** [comment]
Didn't show up yet.

**Comment by hjdhjd** [comment]
It is. 😅

**Comment by DNSGeek** [comment]
Updated to 2.0.3

```
[7/3/2020, 22:19:07] [myQ] Initializing myQ platform...
[7/3/2020, 22:19:23] [myQ] Successfully connected to the myQ API.
[7/3/2020, 22:19:23] [myQ] myQ API error: 404 Not Found
[7/3/2020, 22:19:23] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 22:19:37] [myQ] myQ API error: 404 Not Found
[7/3/2020, 22:19:37] [myQ] myQ API error: unable to refresh. Will retry later.
```

**Comment by DNSGeek** [comment]
I set verbose to true in the config. If you want to have it log debugging info, I'll be glad to post it.

**Comment by boomboxtycoon** [comment]
> Updated to 2.0.3
> 
> ```
> [7/3/2020, 22:19:07] [myQ] Initializing myQ platform...
> [7/3/2020, 22:19:23] [myQ] Successfully connected to the myQ API.
> [7/3/2020, 22:19:23] [myQ] myQ API error: 404 Not Found
> [7/3/2020, 22:19:23] [myQ] myQ API error: unable to refresh. Will retry later.
> [7/3/2020, 22:19:37] [myQ] myQ API error: 404 Not Found
> [7/3/2020, 22:19:37] [myQ] myQ API error: unable to refresh. Will retry later.
> ```

Confirm, same here

**Comment by hjdhjd** [comment]
Try 2.0.4 folks. Let's see if that helps.

**Comment by hjdhjd** [comment]
The trouble with bugs like this is that I can't see it / play with it to fix it directly, because for me...everything works. Grumble.

**Comment by DNSGeek** [comment]
2.0.4

```
[7/3/2020, 22:28:02] [myQ] Initializing myQ platform...
[7/3/2020, 22:28:17] [myQ] Successfully connected to the myQ API.
[7/3/2020, 22:28:17] [myQ] myQ API error: 404 Not Found
[7/3/2020, 22:28:17] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 22:28:32] [myQ] myQ API error: 404 Not Found
[7/3/2020, 22:28:32] [myQ] myQ API error: unable to refresh. Will retry later.
[7/3/2020, 22:28:47] [myQ] myQ API error: 404 Not Found
[7/3/2020, 22:28:47] [myQ] myQ API error: unable to refresh. Will retry later.
```

Is there any other info I can try to get for you that might help?

**Comment by shamoon** [comment]
I dont think this has anything to do with MyQ throttling, as others have pointed out many plugins (homebridge-chamberlain, for example) have been using this version of the API for some time. 

I think there's an actual error in the code, it seems to be pulling the wrong ID. Your `checkStatus` method logs "error logging in" even when the error is not on login, in my case (and Im guessing others) its the /Devices call. I added some logging, and its trying the URL https://api.myqdevice.com/api/v5.1/Accounts/XXXXX/Devices?filterOn=true and getting a 404. That XXXXX ID seems wrong, its the userID which doesnt work for me when I test in Postman (and the URL Accounts/XXX/ suggests its expecting an account ID, not a user ID). Im not sure how its working for you at all but if I sub in my account ID it does.

I submitted a PR #56 to use accountID instead, this allows me to actually login without 404s, the plugin now reports:
`myQ garagedoor device discovered: Garage Door XXX` but of course still nothing in HK but I have a feeling thats a different bug...

**Comment by hjdhjd** [comment]
@shamoon The throttling problem was fixed in 2.0.2. That's not the issue.

**Comment by hjdhjd** [comment]
As to accountID versus userID...both can work, it would seem. And depending on who you are, one does or the other does.

**Comment by shamoon** [comment]
Perhaps userID works sometimes but the API URL is ..../Accounts/XXX/Devices, it clearly implies account ID. Thats also what other plugins use. My hunch is `userID` works sometimes, `accountID` works always. Obviously I cant be sure.

**Comment by hjdhjd** [comment]
Let's give it a whirl. Give me a few.

**Comment by hjdhjd** [comment]
Try updated to 2.0.5 guys. @shamoon - thanks for pointing me in the right direction. Your PR was almost pristine...appreciated, even if I didn't import it directly.

**Comment by TheEngineerGuy** [comment]
Seems to be working. Discovered right away!

**Comment by DNSGeek** [comment]
Yep. Worked for me as soon as I updated.

**Comment by TheEngineerGuy** [comment]
Ok, but garage door is not showing up though.

**Comment by hjdhjd** [comment]
Glad to hear it. Closing this one out.

**Comment by shamoon** [comment]
Its your repo, do as you please but etiquette might dictate if you use 90% of someone's PR you merge it from that person and make your modifications after...

And I figured out the other bug causing no devices in HomeKit (at least for me). See PR #57

**Comment by hjdhjd** [comment]
@shamoon Honestly...you're right. Sadly, my serious coding days are well behind me and this is my fun and relaxation side projects...and Github and the nuances of how to handle merges and commits aren't things I get a lot practice in. I'm not used to having coding collaborators and frankly I don't want to screw up a merge...so when I'm not planning on taking the entirety of a PR, I glean through it, make edits on my end or if I want to take a different path, I do, and then publish.

If you've got the patience for the occasional screw up, happy to play a bit more with it...but I'm certain I'm going to screw this up at least a couple of times. :smile:

**Comment by shamoon** [comment]
No worries, that all makes sense, appreciate it. Github especially makes it very easy to make suggestions on a PR and also after merging it you can always still test & make your own modifications before releasing it (PRs on repositories like this that use a package manager shouldn't contain updates to package.json etc so its not like any changes you merge immediately get pushed out). IMHO strongest HB plugins (open source projects in general) are the ones with the best collaboration!

**Comment by hjdhjd** [comment]
Suggestions as in discussions (like this one)? Or...something else? As someone who has led a couple of decent size open source projects many many moons ago, I couldn't agree with you more on the collaborative approach. :smile:

**Comment by shamoon** [comment]
Yea there’s some cool shit if you dig around where you can comment on specific lines in a PR, have little sub-discussions, suggest code changed and apply them directly etc. I mean it’s usually overkill for small stuff like this but it’s kinda awesome

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request
