### ISSUE TITLE
Not registered plugin?

### ISSUE THREAD

**Issue by boomboxtycoon** [hjdhjd/homebridge-myq2#54]
Since update to 2.0 I’m getting a crash, see below. Should I uninstall/ reinstall? Takes out homebridge too; Thanks for the help
[37m[7/4/2020, 2:19:29 AM] [39m[31mError: The requested platform 'MyQ2' was not registered by any plugin.[39m
[31m    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)[39m
[31m    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)[39m
[31m    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)[39m
[31m    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)[39m
[31m    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)[39m
[31m    at Module._compile (internal/modules/cjs/loader.js:955:30)[39m
[31m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)[39m
[31m    at Module.load (internal/modules/cjs/loader.js:811:32)[39m
[37m[7/4/2020, 2:19:29 AM] [39mGot SIGTERM, shutting down Homebridge...
[37m[7/4/2020, 2:19:37 AM] [39mLoaded config.json with 1 accessories and 3 platforms.

**Comment by zirdum** [comment]
I'm getting this as well:
Error loading platform requested in your config.json at position 5
[7/3/2020, 7:46:46 PM] Error: The requested platform 'MyQ2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[7/3/2020, 7:46:46 PM] Got SIGTERM, shutting down Homebridge...


I also tried it with the platform named MyQ (without the 2 as it's that way in the github page, which is different than the NPM page), and it gives me the same error.

**Comment by zirdum** [comment]
I figured it out...

The config is changed.... and it's case sensitive. Use "platform": "myQ" in your config file.

**Comment by gh0sti** [comment]
after changing the config to myQ I was getting a 404 error for the plugin logging in. This update really screwed up my garage door showing up in homekit

**Comment by cuellarfr** [comment]
I changed the platform name to myQ, but after that I got the 404 error too. I can provide logs if that helps.

**Comment by jlg89** [comment]
7/3/2020, 10:10:11 PM The requested platform "myQ" was not registered by any plugin.
7/3/2020, 10:10:11 PM Your config.json is requesting the platform "myQ" which has not been published by any installed plugins.

From the "platforms" section of config.json:

        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq2"
            },
            "email": "**********",
            "password": "********"
        }

**Comment by hjdhjd** [comment]
I give up on asking people to read READMEs. :smile:

**Comment by jlg89** [comment]
Where is this in the README? I followed the "Configuration" instructions, but I get the same exact error. When I remove the "plugin-map" bit, it automatically gets reinserted into the config.json outside of the platform statement, and still doesn't work:

        {
            "platform": "myQ",
            "email": "****",
            "password": "****"
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-myq2"
            }
        }

**Comment by hjdhjd** [comment]
@jlg89 See "What's new in 2.0" Second paragraph. :smile: Thanks for catching the additional typo though. But it **is** in the README.

**Comment by hjdhjd** [comment]
@jlg89 https://github.com/hjdhjd/homebridge-myq2/blob/master/README.md#things-to-be-aware-of

**Comment by RCdiy** [comment]
Why would we look at a readme for an update using the web ui?
Thanks for your work especially over the holidays 👍

**Comment by jlg89** [comment]
I never could get the update working, even after yanking it all out by the roots and reinstalling, even though I've read and followed the README. Homebridge kept complaining about the plugin not being registered etc. and the garage door wouldn't show up in HomeKit. Finally had to switch to homebridge-chamberlain, which worked immediately.

**Comment by hjdhjd** [comment]
The platform name needs to be correct. Change it from MyQ2 to myQ. It’s a subtle difference. The README is correct. Ensure you’re on the latest 2.0.8.

@jlg89 What is the config.json that you are using, and what is the setup you have? This release has been tested and is working by others, so let’s see what is unique here.

**Comment by zirdum** [comment]
I'm having a similar issue with this plugin. I'm getting this now in my logs:
[7/3/2020, 10:38:54 PM] [myQ] myQ garagedoor device discovered: Garage Door Opener - CG085003A730.
[7/3/2020, 10:38:54 PM] [myQ] myQ gateway device discovered: ZHQ - GW0B0003DF46.

But, I'm not seeing the garage door in the home app. I'm using the docker version of homebridge if that matters.

**Comment by hjdhjd** [comment]
@zirdum What version of the plugin are you on?

**Comment by hjdhjd** [comment]
> Why would we look at a readme for an update using the web ui?
> Thanks for your work especially over the holidays 👍

@jlg89 Perhaps it’s my old school way of thinking but...never, ever, ever, ever install an update without understanding what it will do to your system or setup is always the wisest course of action.

Is there a better place to inform people of breaking changes? The major version bump is the convention to indicate new / breaking changes.

I don’t use the UI, but recognize others do...so if there’s a way to make the experience better, or you’ve seen other plugins do it, point me in that direction. Thanks.

**Comment by zirdum** [comment]
> @zirdum What version of the plugin are you on? The above shows that the plugin is correctly installed and is up and running (all good things)...

Ah, was on 2.0.4... 2.0.8 (latest) works! Thank you!

**Comment by haroutig** [comment]
I'm in the same boat. #59

**Comment by cuellarfr** [comment]
> > Why would we look at a readme for an update using the web ui?
> 
> > Thanks for your work especially over the holidays 👍
> 
> 
> 
> @jlg89 Perhaps it’s my old school way of thinking but...never, ever, ever, ever install an update without understanding what it will do to your system or setup is always the wisest course of action.
> 
> 
> 
> Is there a better place to inform people of breaking changes? The major version bump is the convention to indicate new / breaking changes.
> 
> 
> 
> I don’t use the UI, but recognize others do...so if there’s a way to make the experience better, or you’ve seen other plugins do it, point me in that direction. Thanks.

In the web UI, some plugins show the changelog before you apply the update. No idea how difficult to implement this is, but that would be the perfect place to warn about things like config changes. This plugin has been rock solid for me since December, thanks so much!

**Comment by jlg89** [comment]
> @jlg89 Perhaps it’s my old school way of thinking but...never, ever, ever, ever install an update without understanding what it will do to your system or setup is always the wisest course of action.
> 
> Is there a better place to inform people of breaking changes? The major version bump is the convention to indicate new / breaking changes.

First, let me back up a bit and be very clear that I appreciate your work, and the feedback that I offer is with the goal of improvement, in the quality of the plugin and/or in my understanding of how it works.

The README is absolutely the correct place to inform people of breaking changes. That's not the problem; I did read the README, albeit after I clicked the "update" button on the MyQ plugin in HOOBS, and it completely stopped working...but even following the README didn't get me going again. I think one of the "things to be aware of" in v2 should be something along the lines of, "If you have a working v1 configuration, v2 might completely break it. If this happens, click here for possible fixes."

I still don't know exactly what those fixes might be, because I wasn't able to get the plugin working again. It probably has something to do with the dregs in config.json, because I had to manually remove those in order to get rid of the error messages, even after uninstalling homebridge-myq2.

**Comment by hjdhjd** [comment]
@jlg89 Thanks for elaborating. I'll be more precise in the README. The plugin **is** working for the vast majority of folks. If you're still having issues, post your config.json and let's take a look. Ensure you're on v2.0.8 of the plugin as well. Thanks!

**Comment by haroutig** [comment]
> @jlg89 Thanks for elaborating. I'll be more precise in the README. The plugin **is** working for the vast majority of folks. If you're still having issues, post your config.json and let's take a look. Ensure you're on v2.0.8 of the plugin as well. Thanks!

I have my config posted for this exact problem in an open issue if you want to take a look: #59

**Comment by boomboxtycoon** [comment]
All working over here, thank you very much for the updates! Lots of work, I know, thank you for your time!

**Comment by haroutig** [comment]
> All working over here, thank you very much for the updates! Lots of work, I know, thank you for your time!

What steps did you take that got it working for you?

**Comment by boomboxtycoon** [comment]
Modified the platform name, passed out, updated to 2.0.8 this morning, then a HB restart. Got an instant garage closed on restart and it was now in the Home app.
