### ISSUE TITLE
Append Door State and state changes in HB logs

### ISSUE THREAD

**Issue by TheEngineerGuy** [hjdhjd/homebridge-myq2#58]
@hjdhjd One thing I miss from your previous plugin was the ability to see door opening, open, closing, closed log updates in HB Logs. Can we add that?

EDIT: Not urgent, just nice to have for TShoot purposes.

**Comment by hjdhjd** [comment]
@TheEngineerGuy can you be more specific? What’s the ask, exactly? That state changes are recorded regardless of whether they were initiated in HomeKit or not?

**Comment by TheEngineerGuy** [comment]
@hjdhjd You know the HB log which is visible, it no longer shows when this plugin records a particular state for door.

In the past, if I would open Home App, HB Log would say:
[Garage Door] ....... Closed

When I would open using HomeKit or otherwise, it would say:
[Garage Door] ....... Opening
[Garage Door] ....... Opened

When I would Close using HomeKit or otherwise, it would say:
[Garage Door] ....... Closing
[Garage Door] ....... Closed

I kind of miss this.

**Comment by hjdhjd** [comment]
But you get that. The logs will say:

```
Opening MyQ Garage Door
Closing MyQ Garage Door
```

So I’m missing what the ask is.

**Comment by TheEngineerGuy** [comment]
My Apologies:
What is missing is the final state recorded. Such as opened or closed.

**Comment by hjdhjd** [comment]
Ah. I'll take that on at some point in the near future. Closing this one out...it'll be in an upcoming update @TheEngineerGuy.

**Comment by hjdhjd** [comment]
@TheEngineerGuy a little something for you in 2.0.9...thanks for all your help in the past couple of days. Statuses should be logged now. :smile:

**Comment by TheEngineerGuy** [comment]
Worked like a charm. Thanks @hjdhjd. Love it.
