### ISSUE TITLE
The requested platform "myQ" was not registered by any plugin.

### ISSUE THREAD

**Issue by haroutig** [hjdhjd/homebridge-myq2#59]
I went through previous issues and i could not solve what is wrong with my config. I uninstalled and reinstalled multiple times, made sure the config.json is clean and no remnants of old configs are there and restarted hb multiple times as well. Followed the formatting to the letter and i still see this error in logs. This is what is in my config:

{
            "platform": "myQ",
            "email": “***********”,
            "password": “*********”,
            "plugin_map": {
                "plugin_name": "homebridge-myq2"
            }
}

**Comment by mjtarr** [comment]
I am having a similar problem. After the update, no accessory appears. In the logs, I get:

7/4/2020, 8:34:09 AM Bridge is running on port 51826.7/4/2020, 8:35:49 AM Got SIGINT, shutting down Bridge...7/4/2020, 8:35:53 AM Loaded plugin "homebridge-myq2".7/4/2020, 8:35:53 AM The requested platform "MyQ2" was not registered by any plugin.7/4/2020, 8:35:53 AM Your config.json is requesting the platform "MyQ2" which has not been published by any installed plugins.

Homekit shows HOOBS, but no accessories/garage door to add. Here is what appears in the HOOBS configuration file:

   "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq2"
            },
            "email": "xxx@gmail.com",
            "password": "xxx",
            "gateways": [],
            "openers": []
        }
    ]
}

**Comment by Timeteo** [comment]
+1

**Comment by Vermyndax** [comment]
Same... after the update, it has actually crashed my entire Homebridge and sent it into a restart loop.

**Comment by Vermyndax** [comment]
Jul  4 09:05:52 astaroth systemd[1]: Started Homebridge.
Jul  4 09:05:52 astaroth homebridge[12849]: [7/4/2020, 9:05:52 AM] Loaded config.json with 0 accessories and 3 platforms.
Jul  4 09:05:52 astaroth homebridge[12849]: [7/4/2020, 9:05:52 AM] ---
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Loaded plugin: homebridge-alexa@0.4.73
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Registering platform 'homebridge-alexa.Alexa'
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] ---
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Loaded plugin: homebridge-config-ui-x@4.23.2
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Registering platform 'homebridge-config-ui-x.config'
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] ---
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Loaded plugin: homebridge-myq2@2.0.8
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Registering platform 'homebridge-myq2.myQ'
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] ---
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Loaded plugin: homebridge-roku@3.0.1
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Registering accessory 'homebridge-roku.Roku'
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] ---
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Loaded plugin: homebridge-smartthings-tonesto7@1.5.16
Jul  4 09:05:53 astaroth homebridge[12849]: Homebridge Version: 2.6
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Registering platform 'homebridge-smartthings-tonesto7.SmartThings'
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] ---
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Loading 3 platforms...
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] [Config] Initializing config platform...
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] [Config] Spawning homebridge-config-ui-x with PID 12885
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] [Alexa] Initializing Alexa platform...
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] [Alexa] homebridge-alexa v0.4.73, node v12.18.1, homebridge v1.1.1
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Initializing platform accessory 'Alexa'...
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Error loading platform requested in your config.json at position 3
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Error: The requested platform 'MyQ2' was not registered by any plugin.
Jul  4 09:05:53 astaroth homebridge[12849]:     at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
Jul  4 09:05:53 astaroth homebridge[12849]:     at /usr/lib/node_modules/homebridge/src/server.ts:387:37
Jul  4 09:05:53 astaroth homebridge[12849]:     at Array.forEach (<anonymous>)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
Jul  4 09:05:53 astaroth homebridge[12849]:     at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Jul  4 09:05:53 astaroth homebridge[12849]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Jul  4 09:05:53 astaroth homebridge[12849]:     at internal/main/run_main_module.js:17:47
Jul  4 09:05:53 astaroth homebridge[12849]: [7/4/2020, 9:05:53 AM] Got SIGTERM, shutting down Homebridge...
Jul  4 09:05:55 astaroth homebridge[12849]: #033[0;37m[7/4/2020, 9:05:55 AM] #033[0m#033[0;36m[Config]#033[0m #033[0;33mHomebridge Config UI X v4.23.2 is listening on :: port 8080#033[0m
Jul  4 09:05:58 astaroth systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jul  4 09:05:58 astaroth systemd[1]: homebridge.service: Failed with result 'exit-code'.
Jul  4 09:06:01 astaroth systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Jul  4 09:06:01 astaroth systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 35.
Jul  4 09:06:01 astaroth systemd[1]: Stopped Homebridge.

**Comment by Timeteo** [comment]
> +1
Resolved.
I see the "platform" in the config changed from "MyQ2" to "myQ". Just an upgrade added "myQ" but left "MyQ2". I think that is what causes the issue because by removing all references in config and reinstalling appears to be working now.

**Comment by Timeteo** [comment]
@Vermyndax same for me (even after uninstall) until I removed all references to MyQ in the config. Cleaning out all myQ config enteries, and then re-installing the plugin solved it all for me.

**Comment by Vermyndax** [comment]
Thanks @Timeteo that resolved me as well.

**Comment by Vermyndax** [comment]
All I did was hand-edit the config.json in the terminal and change it to "myQ" as per your suggestion.

**Comment by haroutig** [comment]
unfortunately none of these worked for me...

**Comment by z0rak** [comment]
Same here, under hoobs:

**Comment by z0rak** [comment]
same here, using hoobs 3.2.6:  ```7/4/2020, 10:38:35 AM HOOBS listening on port 80.
7/4/2020, 10:38:38 AM Loaded plugin "homebridge-myq2".
7/4/2020, 10:38:38 AM Loaded plugin "homebridge-nest".
7/4/2020, 10:38:40 AM Loaded plugin "homebridge-ring".
7/4/2020, 10:38:41 AM Loaded plugin "homebridge-zway-kevindayton".
7/4/2020, 10:38:41 AM [Nest] Fetching Nest devices.
7/4/2020, 10:38:41 AM The requested platform "myQ" was not registered by any plugin.
7/4/2020, 10:38:41 AM Your config.json is requesting the platform "myQ" which has not been published by any installed plugins.
7/4/2020, 10:38:41 AM [Ring] Configuring cached accessory 77390486-20ea-48ba-ade2-a4356554ff3e Front Door
7/4/2020, 10:38:41 AM [Ring] Configuring cached accessory b91c0323-bcd0-418a-9cbf-e6c407af0d57 Downstairs
7/4/2020, 10:38:42 AM [ZWayServer] Initializing platform accessory "Kwikset888"...
7/4/2020, 10:38:43 AM [Ring] Configuring 1 cameras and 2 devices for location "Winter Garden" - locationId: 50021d64-f8da-429f-94c8-fc05409cf8c6
7/4/2020, 10:38:45 AM [Nest] initing thermostat "Hallway Thermostat": deviceId: 6416660000057AD3 structureId: 1b237450-961a-11e1-87d8-1231390ce254
7/4/2020, 10:38:45 AM [Nest] initing home_away_sensor "Home Occupied": deviceId: 1b237450-961a-11e1-87d8-1231390ce254 structureId: 1b237450-961a-11e1-87d8-1231390ce254
7/4/2020, 10:38:45 AM [Nest] Initializing platform accessory "Hallway Thermostat"...
7/4/2020, 10:38:45 AM [Nest] Initializing platform accessory "Home Occupied"...
7/4/2020, 10:38:45 AM Bridge is running on port 51826.```

uninstalled/installed/cleared cached accessories/reboot, nothing has worked so far

config.json correctly references 'myQ':

```{
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq2",
                "email": "XXX",
                "password": "XXX"
            }
        }```

**Comment by haroutig** [comment]
A full uninstall/reinstall of homebridge doesn't solve the issue...

**Comment by jlg89** [comment]
https://github.com/hjdhjd/homebridge-myq2/issues/54#issuecomment-653779261

**Comment by hjdhjd** [comment]
@haroutig What version of the plugin are you using? What is the exact homebridge setup you have? Let's see what we can figure out here.

**Comment by haroutig** [comment]
> @haroutig What version of the plugin are you using? What is the exact homebridge setup you have? Let's see what we can figure out here.

using the latest version (2.0.8) I have been uninstalling, cleaning and reinstalling as updates have released. I am running HOOBS in a docker container. Every other plugin, including yours worked fine until last week, other ones still work now.

**Comment by hjdhjd** [comment]
I'm afraid I don't use HOOBS. I use homebridge directly, so I can't meaningfully help troubleshoot issues on that front.

What log entries do you see relating to myQ? Your config (minus the plugin_map pieces) looks okay at the moment.

**Comment by haroutig** [comment]
> I'm afraid I don't use HOOBS. I use homebridge directly, so I can't meaningfully help troubleshoot issues on that front.
> 
> What log entries do you see relating to myQ? Your config (minus the plugin_map pieces) looks okay at the moment.

HOOBS is essentially a webUI for homebridge, the core is the same, which is why it worked fine up to last week and why everything else still works. the only entries i see are:

-Plugin "homebridge-myq2" installed.
-Loaded plugin "homebridge-myq2".
-The requested platform "myQ" was not registered by any plugin.
-Your config.json is requesting the platform "myQ" which has not been published by any installed plugins.

**Comment by haroutig** [comment]
I set up a new installation and did everything from scratch and it seems to finally be working for now. Weird because I'm using the same plugins and i copied over the config.json. I'll mark this closed.

**Comment by RCdiy** [comment]
@haroutig are you suggesting we all do everything from scratch? I did an uninstall and have the same problem. Actually my home bridge no longer works.
```
[7/4/2020, 14:38:16] Loading 4 platforms...
[7/4/2020, 14:38:16] [Config] Initializing config platform...
[7/4/2020, 14:38:16] [Config] Running in Service Mode
[7/4/2020, 14:38:16] Error loading platform requested in your config.json at position 2
[7/4/2020, 14:38:18] Error: The requested platform 'MyQ2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[7/4/2020, 14:38:18] Got SIGTERM, shutting down Homebridge...
[7/4/2020, 14:38:23] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/4/2020, 14:38:28] [HB Supervisor] Restarting Homebridge...
[7/4/2020, 14:38:28] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/4/2020, 14:38:28] [HB Supervisor] Started Homebridge v1.1.1 with PID: 7651
[7/4/2020, 14:38:37] [Config] Starting terminal session
[7/4/2020, 14:38:37] [Config] Starting terminal session
```

**Comment by haroutig** [comment]
> @haroutig are you suggesting we all do everything from scratch? I did an uninstall and have the same problem. Actually my home bridge no longer works.
> 
> ```
> [7/4/2020, 14:38:16] Loading 4 platforms...
> [7/4/2020, 14:38:16] [Config] Initializing config platform...
> [7/4/2020, 14:38:16] [Config] Running in Service Mode
> [7/4/2020, 14:38:16] Error loading platform requested in your config.json at position 2
> [7/4/2020, 14:38:18] Error: The requested platform 'MyQ2' was not registered by any plugin.
>     at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
>     at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
>     at Array.forEach (<anonymous>)
>     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
>     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
>     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
> [7/4/2020, 14:38:18] Got SIGTERM, shutting down Homebridge...
> [7/4/2020, 14:38:23] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
> [7/4/2020, 14:38:28] [HB Supervisor] Restarting Homebridge...
> [7/4/2020, 14:38:28] [HB Supervisor] Starting Homebridge with extra flags: -I
> [7/4/2020, 14:38:28] [HB Supervisor] Started Homebridge v1.1.1 with PID: 7651
> [7/4/2020, 14:38:37] [Config] Starting terminal session
> [7/4/2020, 14:38:37] [Config] Starting terminal session
> ```

No, I am not suggesting everyone do this. If you can get it to work using the fixes referenced in older issues then great. This was the last resort option i went for, if nothing else works, then it is your choice if you want to go the nuclear route.

**Comment by abraver** [comment]
I'm afraid I'm in the same boat, on HOOBS.

Config:

    {      "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq2"
            },
            "email": "****",
            "password": "****"
    }

Logs:

    7/4/2020, 2:57:18 PM The requested platform "myQ" was not registered by any plugin.
    7/4/2020, 2:57:18 PM Your config.json is requesting the platform "myQ" which has not been published by any installed plugins.`

I've tried uninstalling and reinstalling the plugin, checked that the platform name was correct, but no luck yet.
