### ISSUE TITLE
Update no release notes

### ISSUE THREAD

**Issue by RCdiy** [hjdhjd/homebridge-myq2#61]
Web ui
iPod touch 
Safari 
On selecting update it starts immediately without showing the release notes.

**Comment by hjdhjd** [comment]
The website README are the release notes. I have no idea what you’re referencing, can you explain in more detail?

**Comment by elkaboing** [comment]
They’re probably updating through Config UI X which will provide release notes for some plugins.

**Comment by hjdhjd** [comment]
I'll ensure the README and CHANGELOG is included in the distribution bundle for the next release. I think that should do the trick.

**Comment by hjdhjd** [comment]
Fixed in 2.0.9.

**Comment by DMBlakeley** [comment]
Change log displayed but title was 2.0.8 -> 12.0.9  🙂.

**Comment by hjdhjd** [comment]
One. Little. Mistake.
