### ISSUE TITLE
Invalid Username or Password Given - Error

### ISSUE THREAD

**Issue by Moving-Electrons** [hjdhjd/homebridge-myq2#73]
First: thanks for putting together such a great plugin. I updated to the new 2.0 version of the plugin, and it worked fine for a couple of days (I changed the config settings as indicated in the plugin page). However, after installing version 2.1.0, I'm getting the following errors:

[7/6/2020, 3:18:55 PM] [myQ] Invalid username or password given. Check your login and password.
[7/6/2020, 3:18:55 PM] [myQ] myQ API error: unable to refresh. Will retry later.

I checked the username and password and it was the same I had used before. I actually opened the Liftmaster MyQ App, changed the password and updated the config password with the new one and I get the same error. 

Any thoughts?.

**Comment by hjdhjd** [comment]
Your welcome...happy to contribute to the community.

As to your issue...I haven’t seen this particular issue. I’ve run into brief bouts of issues with the myQ API here and there that can manifest itself as login errors. The other possibility could be related to the API AppID we use to access the myQ API...would you mind just waiting this out for a day and trying again? If it’s still an issue, we can look into more serious troubleshooting.

**Comment by Moving-Electrons** [comment]
Hi, thanks for getting back. The issue resolved itself in the last hours, I guess you were right about the API AppID used for this plugin. Thanks!

**Comment by hjdhjd** [comment]
Closing this issue.
