### ISSUE TITLE
Latest version breaks homebridge with “Not registered by any plugin” error.

### ISSUE THREAD

**Issue by HunterJKirby** [hjdhjd/homebridge-myq2#74]
‘The requested platform "myQ" was not registered by any plugin’ error completely broke homebridge even after uninstalling and clearing the cache. Tried setting config.json to “MyQ” instead of “MyQ2” as suggested on Reddit but to no avail, I had to uninstall Homebridge and start from scratch

**Comment by hjdhjd** [comment]
@HunterJKirby If you can provide more specific details on versions of homebridge, homebridge-myq2, and your setup, we can help troubleshoot. The above doesn’t really tell us much. Thanks.
