### ISSUE TITLE
Fetch error encountered: FetchError (reason: connect EHOSTUNREACH)

### ISSUE THREAD

**Issue by dppeak** [hjdhjd/homebridge-myq2#75]
I'm on the latest version and I keep seeing the following error.

`[7/6/2020, 10:56:54 PM] [myQ] Fetch error encountered: FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/d528cad3-a1a5-4f0a-8bf9-8c3849c296a9/Devices?filterOn=true failed, reason: connect EHOSTUNREACH 40.71.237.40:443
[7/6/2020, 10:56:54 PM] [myQ] myQ API error: unable to refresh. Will retry later.`

It's recurring pretty frequently in the log and I seem to have to press the button in the Home app 3 times before the door will actually open.

**Comment by BlueBeedle** [comment]
Not sure if this helps, but I have this same issue with the Chamberlain plugin as well:

https://github.com/iRayanKhan/homebridge-chamberlain/issues/109

**Comment by gizmotronic** [comment]
EHOSTUNREACH is a network-level error. Here's how the Linux [connect(3)](https://linux.die.net/man/3/connect) documentation describes it:

> The destination host cannot be reached (probably because the host is down or a remote router cannot reach it).

This is Chamberlain's issue to diagnose and resolve. As end users of the  platform, I think our only workaround is to retry until it works.

**Comment by RCdiy** [comment]
Could you edit the issue title by adding (reason: connect EHOSTUNREACH)?
If there are other fetch errors, like #79, it is quick to see that is is not the same.

**Comment by hjdhjd** [comment]
@gizmotronic is correct. There’s not much I can do on this one directly. It reads like a network connectivity issue, not a HomeKit or homebridge-myq2 issue. If you’ve got a way of reliably recreating it, we can work with you to troubleshoot it. Do you have steps you can take to get this error to occur?

**Comment by kepstein** [comment]
I have a similar problem. Here's the error I'm getting. 

```
[7/11/2020, 9:08:47 PM] [MyQ] Unable to login to MyQ, received error: { FetchError: request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: connect EHOSTUNREACH 13.83.97.236:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  message:
   'request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: connect EHOSTUNREACH 13.83.97.236:443',
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH' }
```

**Comment by hjdhjd** [comment]
@kepstein what version of homebridge-myq2 are you running? It doesn't appear to be the current one from the log entry you posted (it references v4 of the API and the current plugin uses v5 since v4 was shutdown on July 1).

**Comment by hjdhjd** [comment]
Closing this one out. Please open a new issue if this is still a problem.

**Comment by kepstein** [comment]
So I think I may have discovered my problem. I have a Homekit enabled router (Eero Pro). I believe the Eero was blocking traffic. When I disabled Homekit security it seems to be working without any interruptions now.
