### ISSUE TITLE
Shared Chamberlain home not seen in plugin

### ISSUE THREAD

**Issue by ocdune** [hjdhjd/homebridge-myq2#77]
If someone shares their Chamberlain home to me in the MyQ app, I'm a guest in their home. This plugin does not find any devices in the shared MyQ home, just in the user's primary MyQ home. If the user doesn't have any devices in their primary MyQ home, no error is given, the only message seen in the logs is:

"Successfully connected to the myQ API". 

Is there any way to use this to connect to a device in a shared MyQ home?

**Thank you for the plugin and work on this**. 

Here are the logs seen in the Homebridge logs. Plugin is running on a Synology in a docker container, updated to the latest version of home bridge and the plugin (2.1.0). All user token and personal info removed from the logs and replaced with "[REDACTED]".

```
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] { SecurityToken: '[REDACTED]' }
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] Successfully connected to the myQ API.
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] Token: [REDACTED]
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] {
  Account: {
    AccessGroups: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]/AccessGroups'
    },
    AccessSchedules: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]/AccessSchedules'
    },
    Address: {
      AddressLine1: '',
      AddressLine2: '',
      City: '',
      Country: {
        Code: 'USA',
        IsEEACountry: false,
        href: 'http://api.myqdevice.com/api/v5/Countries/USA'
      },
      PostalCode: '[REDACTED]',
      State: ''
    },
    ContactName: '[REDACTED]',
    Devices: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]/Devices'
    },
    DirectoryCodeLength: 0,
    Email: '[REDACTED]',
    Id: '[REDACTED]',
    Name: "Primary's Home",
    Roles: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]/Roles'
    },
    TimeZone: 'America/[REDACTED]',
    UserAllowance: 4,
    Users: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]/Users'
    },
    Zones: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]/Zones'
    },
    href: 'http://api.myqdevice.com/api/v5/Accounts/[REDACTED]'
  },
  Address: {
    AddressLine1: '',
    AddressLine2: '',
    City: '',
    Country: {
      Code: 'USA',
      IsEEACountry: false,
      href: 'http://api.myqdevice.com/api/v5/Countries/USA'
    },
    PostalCode: '[REDACTED]',
    State: ''
  },
  Admin: false,
  AnalyticsId: '[REDACTED]',
  CultureCode: 'en',
  DiagnosticDataOptIn: false,
  Email: '[REDACTED]',
  FirstName: '[REDACTED]',
  LastName: '[REDACTED]',
  MailingListOptIn: false,
  Phone: '',
  RequestAccountLinkInfo: false,
  TimeZone: { Id: 'America/[REDACTED]', Name: 'America/[REDACTED]' },
  UserId: '[REDACTED]',
  UserName: '[REDACTED]',
  Users: { href: 'http://api.myqdevice.com/api/v5/My/Users' }
}
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] myQ accountID: [REDACTED]
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] {
  count: 0,
  href: 'http://api.myqdevice.com/api/v5/accounts/[REDACTED]',
  items: []
}
[7/8/2020, 9:34:22 AM] [Homebridge MyQ] Throttling myQ API call. Using cached data from the past five seconds.
[7/8/2020, 9:34:37 AM] [Homebridge MyQ] {
  count: 0,
  href: 'http://api.myqdevice.com/api/v5/accounts/[REDACTED]/devices',
  items: []
}
[7/8/2020, 9:34:37 AM] [Homebridge MyQ] Throttling myQ API call. Using cached data from the past five seconds.
```

**Comment by hjdhjd** [comment]
Interesting use case...I’d love to come back and dive into this one, but I need to finish addressing a couple of other bugs first...just wanted to let you know it’s on the radar. What would be helpful in the meantime is if you could repost the above (or use the edit feature, to encase the logs in a code block so it’s a bit more readable. Thanks!

**Comment by ocdune** [comment]
Thanks. I've updated the original post to show that as code. 

Originally I wanted to use a guest user for my home bridge setup, just for security reasons. But now I'm a guest at another property and would love to be able to control it through Siri as well. Appreciate the help.

**Comment by hjdhjd** [comment]
@ocdune Thanks for updating the above...there doesn't seem to be much to work with. From my glance through the above...there's no way to tell that you're in a shared home situation and pull the information into HomeKit. It doesn't seem that this information is exposed in the myQ API (or if it is, it doesn't seem to be reverse-engineered yet).

**Comment by ocdune** [comment]
thanks, appreciate you looking at it.
