### ISSUE TITLE
Lockitron Support

### ISSUE THREAD

**Issue by robertgranholm** [hjdhjd/homebridge-myq2#81]
I have a Lockitron lock connected to MyQ via a hub, it shows up in the app no problem.

I've setup and configured homebridge-myq2 and get success for API access and finding the hub, however, I don't see the lock or the "opener" I would guess it's referred to in the home app at all, what am I missing?

[7/10/2020, 11:47:38 AM] [MyQ Lock] Successfully connected to the myQ API.
[7/10/2020, 11:47:38 AM] [MyQ Lock] myQ gateway device discovered: MyQ Hub (serial number: GW25000XXXXX).

Thank you!!

**Comment by dxdc** [comment]
@robertgranholm It sounds like your problem is here:

```js
      // We are only interested in garage door openers. Perhaps more types in the future.
      if(!device.device_family || device.device_family.indexOf("garagedoor") === -1) {
        return;
      }
```

You would need to add support for a lock. I added a PR here: https://github.com/hjdhjd/homebridge-myq2/pull/84/files that I think at least helps notify you to the problem.

**Comment by hjdhjd** [comment]
@dxdc myQ device discovery will always be shown, whether or not we ultimately add the accessory to HomeKit. The code you're referencing is for adding the device to HomeKit.

The discovery messages above are the ones that are exposed via myQ and aren't what is configured. If it doesn't show up there, that means that myQ doesn't know about it. If myQ doesn't know about it...then we can't do much about it. The PR you mentioned above won't catch it either...because the device is never sent to us via myQ to begin with! :smile:

@robertgranholm Locks aren't supported at the moment, although it's something I'm interested in adding support for if the MyQ API allows for it. If you can turn on debugging and see if the Lockitron or locks are mentioned anywhere, I'd be interested in it for future reference if you wouldn't mind posting the information (redacted of course for anything sensitive).

**Comment by robertgranholm** [comment]
Here you go, hopefully I redacted what was important...would be great if this is an easy add to toggle lock and unlock! Lockitron basically abandoned their product and now MyQ has to pick it up.

===

[7/13/2020, 8:51:11 AM] [MyQ Lock] { SecurityToken: 'xxx' }
[7/13/2020, 8:51:11 AM] [MyQ Lock] Successfully connected to the myQ API.
[7/13/2020, 8:51:11 AM] [MyQ Lock] Token: xxx
[7/13/2020, 8:51:11 AM] [MyQ Lock] {
  Account: {
    AccessGroups: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxx/AccessGroups'
    },
    AccessSchedules: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxx/AccessSchedules'
    },
    Address: {
      AddressLine1: '',
      AddressLine2: '',
      City: '',
      Country: {
        Code: 'USA',
        IsEEACountry: false,
        href: 'http://api.myqdevice.com/api/v5/Countries/USA'
      },
      PostalCode: '19072',
      State: ''
    },
    ContactName: 'Robert Granholm',
    Devices: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxx/Devices'
    },
    DirectoryCodeLength: 0,
    Email: 'xxxx@gmail.com',
    Id: 'xxx',
    Name: 'xxx',
    Roles: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxx/Roles'
    },
    TimeZone: 'America/New_York',
    UserAllowance: 4,
    Users: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxx/Users'
    },
    Zones: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxx/Zones'
    },
    href: 'http://api.myqdevice.com/api/v5/Accounts/xxx'
  },
  Address: {
    AddressLine1: '',
    AddressLine2: '',
    City: '',
    Country: {
      Code: 'USA',
      IsEEACountry: false,
      href: 'http://api.myqdevice.com/api/v5/Countries/USA'
    },
    PostalCode: '19072',
    State: ''
  },
  Admin: false,
  AnalyticsId: '9a9a91d6-66d9-4cdd-99ed-0532d2723631',
  CultureCode: 'en',
  DiagnosticDataOptIn: false,
  Email: 'xxx@gmail.com',
  FirstName: 'Robert',
  LastName: 'Granholm',
  MailingListOptIn: false,
  Phone: '',
  RequestAccountLinkInfo: false,
  TimeZone: { Id: 'America/New_York', Name: 'America/New_York' },
  UserId: 'xxx',
  UserName: 'xxx@gmail.com',
  Users: { href: 'http://api.myqdevice.com/api/v5/My/Users' }
}
[7/13/2020, 8:51:11 AM] [MyQ Lock] myQ accountID: xxx
[7/13/2020, 8:51:11 AM] [MyQ Lock] {
  count: 1,
  href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices',
  items: [
    {
      created_date: '2020-06-08T21:59:51.937',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'hub',
      href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C',
      name: 'MyQ Hub',
      serial_number: 'xxx',
      state: {
        firmware_version: '2.11',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-07-12T20:45:28.7226797Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [Array],
        updated_date: '2020-07-12T20:45:31.751314Z'
      }
    }
  ]
}
[7/13/2020, 8:51:11 AM] [MyQ Lock] myQ gateway discovered: MyQ Hub (serial number: xxx).
[7/13/2020, 8:51:11 AM] [MyQ Lock] {
  created_date: '2020-06-08T21:59:51.937',
  device_family: 'gateway',
  device_platform: 'myq',
  device_type: 'hub',
  href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C',
  name: 'MyQ Hub',
  serial_number: 'GW250000093C',
  state: {
    firmware_version: '2.11',
    homekit_capable: false,
    homekit_enabled: false,
    last_status: '2020-07-12T20:45:28.7226797Z',
    learn: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C/learn',
    learn_mode: false,
    online: true,
    pending_bootload_abandoned: false,
    physical_devices: [ 'CG08461F6BC1', 'CG08461F6BC2' ],
    updated_date: '2020-07-12T20:45:31.751314Z'
  }
}
[7/13/2020, 8:51:11 AM] [MyQ Lock] Throttling refreshDevices API call. Using cached data from the past five seconds.
[7/13/2020, 8:51:11 AM] [MyQ Lock] myQ device category 'gateway' is not currently supported, ignoring: MyQ Hub (serial number: xxx).
[7/13/2020, 8:51:26 AM] [MyQ Lock] {
  count: 1,
  href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices',
  items: [
    {
      created_date: '2020-06-08T21:59:51.937',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'hub',
      href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C',
      name: 'MyQ Hub',
      serial_number: 'GW250000093C',
      state: {
        firmware_version: '2.11',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-07-12T20:45:28.7226797Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [Array],
        updated_date: '2020-07-12T20:45:31.751314Z'
      }
    }
  ]
}
[7/13/2020, 8:51:26 AM] [MyQ Lock] Throttling refreshDevices API call. Using cached data from the past five seconds.
[7/13/2020, 8:51:41 AM] [MyQ Lock] {
  count: 1,
  href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices',
  items: [
    {
      created_date: '2020-06-08T21:59:51.937',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'hub',
      href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C',
      name: 'MyQ Hub',
      serial_number: 'xxx',
      state: {
        firmware_version: '2.11',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-07-12T20:45:28.7226797Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [Array],
        updated_date: '2020-07-12T20:45:31.751314Z'
      }
    }
  ]
}
[7/13/2020, 8:51:41 AM] [MyQ Lock] Throttling refreshDevices API call. Using cached data from the past five seconds.
[7/13/2020, 8:51:56 AM] [MyQ Lock] {
  count: 1,
  href: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices',
  items: [
    {
      created_date: '2020-06-08T21:59:51.937',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'hub',
      href: 'http://api.myqdevice.com/api/v5/accounts/5e6d1809-f7d6-4e03-8563-c9e3ef49d7ac/devices/GW250000093C',
      name: 'MyQ Hub',
      serial_number: 'xxx',
      state: {
        firmware_version: '2.11',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-07-12T20:45:28.7226797Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xxx/devices/GW250000093C/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [Array],
        updated_date: '2020-07-12T20:45:31.751314Z'
      }
    }
  ]
}
[7/13/2020, 8:51:56 AM] [MyQ Lock] Throttling refreshDevices API call. Using cached data from the past five seconds.

**Comment by hjdhjd** [comment]
@robertgranholm I've edited the above so it's enclosed in code tags. :smile:

If it's supportable, happy to do it.

**Comment by hjdhjd** [comment]
Doesn't seem like the lock is exposed at all in the above I'm afraid. Can you try one more thing? Login to www.myliftmaster.com and see if you can see the lock there. If you can, perhaps we can reverse engineer this.

**Comment by robertgranholm** [comment]
Thanks, not promising. It shows in the MyQ app, but if I try to login at myliftmaster.com is says..

Your request has been denied.

[5583776699898778187]

It does take my username and password though...lame! Lockitron had homebridge support really early on

**Comment by hjdhjd** [comment]
Sorry Robert...perhaps when someone reverse engineers the protocol we can support it. Closing this out for now.
