### ISSUE TITLE
Garage state always says opening (everything else works fine)

### ISSUE THREAD

**Issue by armandr** [hjdhjd/homebridge-myq2#86]
I'm able to open and close, and sometimes see the correct state of the door briefly when I tap the icon once and it opens the door.  Notifications when the garage is opened or closed work fine.  

The rest of the time, the state is always stuck on "opening".

![IMG_4881](https://user-images.githubusercontent.com/11222953/87235688-90d6aa00-c3ac-11ea-9f5c-a8f40f096d0e.png)

Anyone else see this issue?

**Comment by hjdhjd** [comment]
Thanks for the report. What version of the plugin are you running?

**Comment by armandr** [comment]
Was 2.0.0.  Sorry just noticed how busy you've been :) 

Upgraded to 2.1.2 will post a new issue if I see it again.
