### ISSUE TITLE
v2.1.1 install issue: ELIFCYCLE Failed at the homebridge-myq2@2.1.1 install script.

### ISSUE THREAD

**Issue by MAscooby** [hjdhjd/homebridge-myq2#87]
pi@raspberrypi:~ $ npm install -g homebridge-myq2

> homebridge-myq2@2.1.1 install /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2
> npm run build

> homebridge-myq2@2.1.1 build /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2
> rimraf ./dist && tsc

sh: 1: tsc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! homebridge-myq2@2.1.1 build: `rimraf ./dist && tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the homebridge-myq2@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-12T20_18_49_195Z-debug.log
npm ERR! code ELIFECYCLEnpm ERR! errno 1
npm ERR! homebridge-myq2@2.1.1 install: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-myq2@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-12T20_18_49_934Z-debug.log
pi@raspberrypi:~ $ more  /home/pi/.npm/_logs/2020-07-12T20_13_13_327Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/pi/.nvm/versions/node/v14.5.0/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v14.5.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-myq2'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v14.5.0
4 verbose npm-session d211f9ae3741666c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-myq2 1139ms
8 http fetch GET 200 https://registry.npmjs.org/homebridge-myq2/-/homebridge-myq2-2.1.1.tgz 851ms
9 silly pacote tag manifest for homebridge-myq2@latest fetched in 2103ms
10 timing stage:loadCurrentTree Completed in 2918ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 130ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule homebridge-myq2@2.1.1 checking installable status
18 silly removeObsoleteDep removing homebridge-myq2@2.1.0 from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing @types/node-fetch@2.5.7 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing @types/node@14.0.19 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing form-data@3.0.0 from the tree as its been replaced by a newer version or is no longer required
22 silly removeObsoleteDep removing asynckit@0.4.0 from the tree as its been replaced by a newer version or is no longer required
23 silly removeObsoleteDep removing combined-stream@1.0.8 from the tree as its been replaced by a newer version or is no longer required
24 silly removeObsoleteDep removing delayed-stream@1.0.0 from the tree as its been replaced by a newer version or is no longer required
25 silly removeObsoleteDep removing mime-types@2.1.27 from the tree as its been replaced by a newer version or is no longer required
26 silly removeObsoleteDep removing mime-db@1.44.0 from the tree as its been replaced by a newer version or is no longer required
27 silly removeObsoleteDep removing node-fetch@2.6.0 from the tree as its been replaced by a newer version or is no longer required
28 silly removeObsoleteDep removing util@0.12.3 from the tree as its been replaced by a newer version or is no longer required
29 silly removeObsoleteDep removing inherits@2.0.4 from the tree as its been replaced by a newer version or is no longer required
30 silly removeObsoleteDep removing is-arguments@1.0.4 from the tree as its been replaced by a newer version or is no longer required
31 silly removeObsoleteDep removing is-generator-function@1.0.7 from the tree as its been replaced by a newer version or is no longer required
32 silly removeObsoleteDep removing is-typed-array@1.1.3 from the tree as its been replaced by a newer version or is no longer required
33 silly removeObsoleteDep removing available-typed-arrays@1.0.2 from the tree as its been replaced by a newer version or is no longer required
34 silly removeObsoleteDep removing array-filter@1.0.0 from the tree as its been replaced by a newer version or is no longer required
35 silly removeObsoleteDep removing foreach@2.0.5 from the tree as its been replaced by a newer version or is no longer required
36 silly removeObsoleteDep removing safe-buffer@5.2.1 from the tree as its been replaced by a newer version or is no longer required
37 silly removeObsoleteDep removing which-typed-array@1.1.2 from the tree as its been replaced by a newer version or is no longer required
38 http fetch GET 304 https://registry.npmjs.org/util 210ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/node-fetch 229ms (from cache)
40 silly pacote range manifest for util@^0.12.3 fetched in 248ms
41 silly resolveWithNewModule util@0.12.3 checking installable status
42 silly pacote range manifest for node-fetch@^2.6.0 fetched in 281ms
43 silly resolveWithNewModule node-fetch@2.6.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/@types%2fnode-fetch 827ms (from cache)
45 silly pacote range manifest for @types/node-fetch@^2.5.7 fetched in 860ms
46 silly resolveWithNewModule @types/node-fetch@2.5.7 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 170ms
48 http fetch GET 304 https://registry.npmjs.org/form-data 230ms (from cache)
49 silly pacote range manifest for form-data@^3.0.0 fetched in 240ms
50 silly resolveWithNewModule form-data@3.0.0 checking installable status
51 http fetch GET 200 https://registry.npmjs.org/@types/node/-/node-14.0.22.tgz 148ms
52 silly pacote range manifest for @types/node@* fetched in 381ms
53 silly resolveWithNewModule @types/node@14.0.22 checking installable status
54 http fetch GET 304 https://registry.npmjs.org/asynckit 127ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/combined-stream 138ms (from cache)
56 silly pacote range manifest for asynckit@^0.4.0 fetched in 144ms
57 silly resolveWithNewModule asynckit@0.4.0 checking installable status
58 silly pacote range manifest for combined-stream@^1.0.8 fetched in 156ms
59 silly resolveWithNewModule combined-stream@1.0.8 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/mime-types 175ms (from cache)
61 silly pacote range manifest for mime-types@^2.1.12 fetched in 184ms
62 silly resolveWithNewModule mime-types@2.1.27 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/delayed-stream 79ms (from cache)
64 silly pacote range manifest for delayed-stream@~1.0.0 fetched in 86ms
65 silly resolveWithNewModule delayed-stream@1.0.0 checking installable status
66 http fetch GET 304 https://registry.npmjs.org/mime-db 87ms (from cache)
67 silly pacote version manifest for mime-db@1.44.0 fetched in 102ms
68 silly resolveWithNewModule mime-db@1.44.0 checking installable status
69 http fetch GET 304 https://registry.npmjs.org/is-arguments 218ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/inherits 222ms (from cache)
71 silly pacote range manifest for is-arguments@^1.0.4 fetched in 250ms
72 silly resolveWithNewModule is-arguments@1.0.4 checking installable status
73 silly pacote range manifest for inherits@^2.0.3 fetched in 256ms
74 silly resolveWithNewModule inherits@2.0.4 checking installable status
75 http fetch GET 304 https://registry.npmjs.org/which-typed-array 280ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/safe-buffer 284ms (from cache)
77 http fetch GET 304 https://registry.npmjs.org/is-typed-array 295ms (from cache)
78 silly pacote range manifest for which-typed-array@^1.1.2 fetched in 297ms
79 silly resolveWithNewModule which-typed-array@1.1.2 checking installable status
80 silly pacote range manifest for safe-buffer@^5.1.2 fetched in 303ms
81 silly resolveWithNewModule safe-buffer@5.2.1 checking installable status
82 silly pacote range manifest for is-typed-array@^1.1.3 fetched in 309ms
83 silly resolveWithNewModule is-typed-array@1.1.3 checking installable status
84 http fetch GET 304 https://registry.npmjs.org/is-generator-function 4220ms (from cache)
85 silly pacote range manifest for is-generator-function@^1.0.7 fetched in 4259ms
86 silly resolveWithNewModule is-generator-function@1.0.7 checking installable status
87 http fetch GET 304 https://registry.npmjs.org/available-typed-arrays 192ms (from cache)
88 http fetch GET 304 https://registry.npmjs.org/foreach 197ms (from cache)
89 http fetch GET 304 https://registry.npmjs.org/has-symbols 200ms (from cache)
90 silly pacote range manifest for available-typed-arrays@^1.0.0 fetched in 216ms
91 silly resolveWithNewModule available-typed-arrays@1.0.2 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/es-abstract 216ms (from cache)
93 silly pacote range manifest for foreach@^2.0.5 fetched in 224ms
94 silly resolveWithNewModule foreach@2.0.5 checking installable status
95 silly pacote range manifest for has-symbols@^1.0.1 fetched in 226ms
96 silly resolveWithNewModule has-symbols@1.0.1 checking installable status
97 silly pacote range manifest for es-abstract@^1.17.4 fetched in 236ms
98 silly resolveWithNewModule es-abstract@1.17.6 checking installable status
99 http fetch GET 304 https://registry.npmjs.org/array-filter 73ms (from cache)
100 silly pacote range manifest for array-filter@^1.0.0 fetched in 81ms
101 silly resolveWithNewModule array-filter@1.0.0 checking installable status
102 http fetch GET 304 https://registry.npmjs.org/es-to-primitive 462ms (from cache)
103 http fetch GET 304 https://registry.npmjs.org/has 459ms (from cache)
104 http fetch GET 304 https://registry.npmjs.org/function-bind 463ms (from cache)
105 http fetch GET 304 https://registry.npmjs.org/is-callable 461ms (from cache)
106 http fetch GET 304 https://registry.npmjs.org/object-inspect 475ms (from cache)
107 http fetch GET 304 https://registry.npmjs.org/is-regex 482ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/string.prototype.trimend 471ms (from cache)
109 http fetch GET 304 https://registry.npmjs.org/object-keys 482ms (from cache)
110 http fetch GET 304 https://registry.npmjs.org/string.prototype.trimstart 481ms (from cache)
111 silly pacote range manifest for has@^1.0.3 fetched in 505ms
112 silly resolveWithNewModule has@1.0.3 checking installable status
113 silly pacote range manifest for es-to-primitive@^1.2.1 fetched in 513ms
114 silly resolveWithNewModule es-to-primitive@1.2.1 checking installable status
115 silly pacote range manifest for function-bind@^1.1.1 fetched in 514ms
116 silly resolveWithNewModule function-bind@1.1.1 checking installable status
117 silly pacote range manifest for is-callable@^1.2.0 fetched in 513ms
118 silly resolveWithNewModule is-callable@1.2.0 checking installable status
119 silly pacote range manifest for object-inspect@^1.7.0 fetched in 515ms
120 silly resolveWithNewModule object-inspect@1.8.0 checking installable status
121 silly pacote range manifest for is-regex@^1.1.0 fetched in 520ms
122 silly resolveWithNewModule is-regex@1.1.0 checking installable status
123 silly pacote range manifest for object-keys@^1.1.1 fetched in 532ms
124 silly resolveWithNewModule object-keys@1.1.1 checking installable status
125 silly pacote range manifest for string.prototype.trimend@^1.0.1 fetched in 526ms
126 silly resolveWithNewModule string.prototype.trimend@1.0.1 checking installable status
127 http fetch GET 304 https://registry.npmjs.org/object.assign 534ms (from cache)
128 silly pacote range manifest for string.prototype.trimstart@^1.0.1 fetched in 533ms
129 silly resolveWithNewModule string.prototype.trimstart@1.0.1 checking installable status
130 silly pacote range manifest for object.assign@^4.1.0 fetched in 547ms
131 silly resolveWithNewModule object.assign@4.1.0 checking installable status
132 http fetch GET 304 https://registry.npmjs.org/is-date-object 104ms (from cache)
133 http fetch GET 304 https://registry.npmjs.org/is-symbol 107ms (from cache)
134 silly pacote range manifest for is-date-object@^1.0.1 fetched in 116ms
135 silly resolveWithNewModule is-date-object@1.0.2 checking installable status
136 silly pacote range manifest for is-symbol@^1.0.2 fetched in 117ms
137 silly resolveWithNewModule is-symbol@1.0.3 checking installable status
138 http fetch GET 304 https://registry.npmjs.org/define-properties 68ms (from cache)
139 silly pacote range manifest for define-properties@^1.1.2 fetched in 75ms
140 silly resolveWithNewModule define-properties@1.1.3 checking installable status
141 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7194ms
142 timing stage:loadIdealTree Completed in 7415ms
143 silly currentTree lib
143 silly currentTree └─┬ homebridge-myq2@2.1.0
143 silly currentTree   ├── @types/node-fetch@2.5.7
143 silly currentTree   ├── @types/node@14.0.19
143 silly currentTree   ├── array-filter@1.0.0
143 silly currentTree   ├── asynckit@0.4.0
143 silly currentTree   ├── available-typed-arrays@1.0.2
143 silly currentTree   ├── combined-stream@1.0.8
143 silly currentTree   ├── define-properties@1.1.3
143 silly currentTree   ├── delayed-stream@1.0.0
143 silly currentTree   ├── es-abstract@1.17.6
143 silly currentTree   ├── es-to-primitive@1.2.1
143 silly currentTree   ├── foreach@2.0.5
143 silly currentTree   ├── form-data@3.0.0
143 silly currentTree   ├── function-bind@1.1.1
143 silly currentTree   ├── has-symbols@1.0.1
143 silly currentTree   ├── has@1.0.3
143 silly currentTree   ├── inherits@2.0.4
143 silly currentTree   ├── is-arguments@1.0.4
143 silly currentTree   ├── is-callable@1.2.0
143 silly currentTree   ├── is-date-object@1.0.2
143 silly currentTree   ├── is-generator-function@1.0.7
143 silly currentTree   ├── is-regex@1.1.0
143 silly currentTree   ├── is-symbol@1.0.3
143 silly currentTree   ├── is-typed-array@1.1.3
143 silly currentTree   ├── mime-db@1.44.0
143 silly currentTree   ├── mime-types@2.1.27
143 silly currentTree   ├── node-fetch@2.6.0
143 silly currentTree   ├── object-inspect@1.8.0
143 silly currentTree   ├── object-keys@1.1.1
143 silly currentTree   ├── object.assign@4.1.0
143 silly currentTree   ├── safe-buffer@5.2.1
143 silly currentTree   ├── string.prototype.trimend@1.0.1
143 silly currentTree   ├── string.prototype.trimstart@1.0.1
143 silly currentTree   ├── util@0.12.3
143 silly currentTree   └── which-typed-array@1.1.2
144 silly idealTree lib
144 silly idealTree └─┬ homebridge-myq2@2.1.1
144 silly idealTree   ├── @types/node-fetch@2.5.7
144 silly idealTree   ├── @types/node@14.0.22
144 silly idealTree   ├── array-filter@1.0.0
144 silly idealTree   ├── asynckit@0.4.0
144 silly idealTree   ├── available-typed-arrays@1.0.2
144 silly idealTree   ├── combined-stream@1.0.8
144 silly idealTree   ├── define-properties@1.1.3
144 silly idealTree   ├── delayed-stream@1.0.0
144 silly idealTree   ├── es-abstract@1.17.6
144 silly idealTree   ├── es-to-primitive@1.2.1
144 silly idealTree   ├── foreach@2.0.5
144 silly idealTree   ├── form-data@3.0.0
144 silly idealTree   ├── function-bind@1.1.1
144 silly idealTree   ├── has-symbols@1.0.1
144 silly idealTree   ├── has@1.0.3
144 silly idealTree   ├── inherits@2.0.4
144 silly idealTree   ├── is-arguments@1.0.4
144 silly idealTree   ├── is-callable@1.2.0
144 silly idealTree   ├── is-date-object@1.0.2
144 silly idealTree   ├── is-generator-function@1.0.7
144 silly idealTree   ├── is-regex@1.1.0
144 silly idealTree   ├── is-symbol@1.0.3
144 silly idealTree   ├── is-typed-array@1.1.3
144 silly idealTree   ├── mime-db@1.44.0
144 silly idealTree   ├── mime-types@2.1.27
144 silly idealTree   ├── node-fetch@2.6.0
144 silly idealTree   ├── object-inspect@1.8.0
144 silly idealTree   ├── object-keys@1.1.1
144 silly idealTree   ├── object.assign@4.1.0
144 silly idealTree   ├── safe-buffer@5.2.1
144 silly idealTree   ├── string.prototype.trimend@1.0.1
144 silly idealTree   ├── string.prototype.trimstart@1.0.1
144 silly idealTree   ├── util@0.12.3
144 silly idealTree   └── which-typed-array@1.1.2
145 silly install generateActionsToTake
146 timing stage:generateActionsToTake Completed in 34ms
147 silly diffTrees action count 2
148 silly diffTrees update @types/node@14.0.22
149 silly diffTrees update homebridge-myq2@2.1.1
150 silly decomposeActions action count 20
151 silly decomposeActions unbuild @types/node@14.0.19
152 silly decomposeActions remove @types/node@14.0.19
153 silly decomposeActions fetch @types/node@14.0.22
154 silly decomposeActions extract @types/node@14.0.22
155 silly decomposeActions preinstall @types/node@14.0.22
156 silly decomposeActions build @types/node@14.0.22
157 silly decomposeActions install @types/node@14.0.22
158 silly decomposeActions postinstall @types/node@14.0.22
159 silly decomposeActions finalize @types/node@14.0.22
160 silly decomposeActions refresh-package-json @types/node@14.0.22
161 silly decomposeActions unbuild homebridge-myq2@2.1.0
162 silly decomposeActions remove homebridge-myq2@2.1.0
163 silly decomposeActions fetch homebridge-myq2@2.1.1
164 silly decomposeActions extract homebridge-myq2@2.1.1
165 silly decomposeActions preinstall homebridge-myq2@2.1.1
166 silly decomposeActions build homebridge-myq2@2.1.1
167 silly decomposeActions install homebridge-myq2@2.1.1
168 silly decomposeActions postinstall homebridge-myq2@2.1.1
169 silly decomposeActions finalize homebridge-myq2@2.1.1
170 silly decomposeActions refresh-package-json homebridge-myq2@2.1.1
171 silly install executeActions
172 silly doSerial global-install 20
173 verbose correctMkdir /home/pi/.npm/_locks correctMkdir not in flight; initializing
174 verbose lock using /home/pi/.npm/_locks/staging-0e1f4c7a7807e56b.lock for /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/.staging
175 silly doParallel extract 2
176 silly extract @types/node@14.0.22
177 silly extract homebridge-myq2@2.1.1
178 silly tarball trying homebridge-myq2@latest by hash: sha512-Lxa2zrm0yg4PRAdOmocrN3Fcc1HTW4aQyi6s/cpbX+fC9sXpiQwUIxt72bGXCiDFImHAT6YnHjKU3yCs7boezQ==
179 silly tarball trying @types/node@* by hash: sha512-emeGcJvdiZ4Z3ohbmw93E/64jRzUHAItSHt8nF7M4TGgQTiWqFVGB8KNpLGFmUHmHLvjvBgFwVlqNcq+VuGv9g==
180 silly extract homebridge-myq2@latest extracted to /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/.staging/homebridge-myq2-1feb3dac (118ms)
181 silly extract @types/node@* extracted to /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/.staging/@types/node-975457de (239ms)
182 timing action:extract Completed in 246ms
183 silly doReverseSerial unbuild 20
184 silly unbuild homebridge-myq2@2.1.0
185 info lifecycle homebridge-myq2@2.1.0~preuninstall: homebridge-myq2@2.1.0
186 info lifecycle homebridge-myq2@2.1.0~uninstall: homebridge-myq2@2.1.0
187 verbose unbuild rmStuff homebridge-myq2@2.1.0 from /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules
188 info lifecycle homebridge-myq2@2.1.0~postuninstall: homebridge-myq2@2.1.0
189 silly unbuild @types/node@14.0.19
190 info lifecycle @types/node@14.0.19~preuninstall: @types/node@14.0.19
191 info lifecycle @types/node@14.0.19~uninstall: @types/node@14.0.19
192 verbose unbuild rmStuff @types/node@14.0.19 from /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules
193 verbose unbuild rmStuff in /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2/node_modules
194 info lifecycle @types/node@14.0.19~postuninstall: @types/node@14.0.19
195 timing action:unbuild Completed in 12ms
196 silly doSerial remove 20
197 silly remove /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2/node_modules/@types/node
198 silly remove /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2
199 timing action:remove Completed in 140ms
200 silly doSerial move 20
201 silly doSerial finalize 20
202 silly finalize /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2/node_modules/@types/node
203 silly finalize /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2
204 timing action:finalize Completed in 37ms
205 silly doParallel refresh-package-json 2
206 silly refresh-package-json /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2/node_modules/@types/node
207 silly refresh-package-json /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2
208 timing action:refresh-package-json Completed in 49ms
209 silly doParallel preinstall 2
210 silly preinstall @types/node@14.0.22
211 info lifecycle @types/node@14.0.22~preinstall: @types/node@14.0.22
212 silly preinstall homebridge-myq2@2.1.1
213 info lifecycle homebridge-myq2@2.1.1~preinstall: homebridge-myq2@2.1.1
214 timing action:preinstall Completed in 3ms
215 silly doSerial build 20
216 silly build @types/node@14.0.22
217 info linkStuff @types/node@14.0.22
218 silly linkStuff @types/node@14.0.22 has /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2/node_modules as its parent node_modules
219 silly linkStuff @types/node@14.0.22 is part of a global install
220 silly linkStuff @types/node@14.0.22 is installed into a global node_modules
221 silly build homebridge-myq2@2.1.1
222 info linkStuff homebridge-myq2@2.1.1
223 silly linkStuff homebridge-myq2@2.1.1 has /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules as its parent node_modules
224 silly linkStuff homebridge-myq2@2.1.1 is part of a global install
225 silly linkStuff homebridge-myq2@2.1.1 is installed into a global node_modules
226 silly linkStuff homebridge-myq2@2.1.1 is installed into the top-level global node_modules
227 timing action:build Completed in 6ms
228 silly doSerial global-link 20
229 silly doParallel update-linked 0
230 silly doSerial install 20
231 silly install @types/node@14.0.22
232 info lifecycle @types/node@14.0.22~install: @types/node@14.0.22
233 silly install homebridge-myq2@2.1.1
234 info lifecycle homebridge-myq2@2.1.1~install: homebridge-myq2@2.1.1
235 verbose lifecycle homebridge-myq2@2.1.1~install: unsafe-perm in lifecycle true
236 verbose lifecycle homebridge-myq2@2.1.1~install: PATH: /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/.nvm/
versions/node/v14.5.0/lib/node_modules/homebridge-myq2/node_modules/.bin:/home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/.bin:/home/pi/.nvm/versions/node/v14.5.0/bin
:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
237 verbose lifecycle homebridge-myq2@2.1.1~install: CWD: /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/homebridge-myq2
238 silly lifecycle homebridge-myq2@2.1.1~install: Args: [ '-c', 'npm run build' ]
239 silly lifecycle homebridge-myq2@2.1.1~install: Returned: code: 1  signal: null
240 info lifecycle homebridge-myq2@2.1.1~install: Failed to exec install script
241 timing action:install Completed in 4549ms
242 verbose unlock done using /home/pi/.npm/_locks/staging-0e1f4c7a7807e56b.lock for /home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/.staging
243 timing stage:rollbackFailedOptional Completed in 585ms
244 timing stage:runTopLevelLifecycles Completed in 16033ms
245 verbose stack Error: homebridge-myq2@2.1.1 install: `npm run build`
245 verbose stack Exit status 1
245 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
245 verbose stack     at EventEmitter.emit (events.js:314:20)
245 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
245 verbose stack     at ChildProcess.emit (events.js:314:20)
245 verbose stack     at maybeClose (internal/child_process.js:1051:16)
245 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
246 verbose pkgid homebridge-myq2@2.1.1
247 verbose cwd /home/pi
248 verbose Linux 4.19.118-v7+
249 verbose argv "/home/pi/.nvm/versions/node/v14.5.0/bin/node" "/home/pi/.nvm/versions/node/v14.5.0/bin/npm" "install" "-g" "homebridge-myq2"
250 verbose node v14.5.0
251 verbose npm  v6.14.6
252 error code ELIFECYCLE
253 error errno 1
254 error homebridge-myq2@2.1.1 install: `npm run build`
254 error Exit status 1
255 error Failed at the homebridge-myq2@2.1.1 install script.
255 error This is probably not a problem with npm. There is likely additional logging output above.
256 verbose exit [ 1, true ]

**Comment by MAscooby** [comment]
Resolved in 2.1.2 ... Thanks! :)

**Comment by hjdhjd** [comment]
@MAscooby Sorry about that! :smile:
