### ISSUE TITLE
Siri no longer can open garage doors.

### ISSUE THREAD

**Issue by MaverickC2** [hjdhjd/homebridge-myq2#88]
Previously, using Siri to open garage doors by name worked. With recent updates it no longer works.

**Comment by hjdhjd** [comment]
Can you provide specifics? What version of the plugin are you using? Can you reliably recreate the issue? If so, can you provide steps to do so. Thanks!

**Comment by MaverickC2** [comment]
Running version v2.1.2.

Steps to recreate:
Ask Siri: "Open {Garage Door Name}"

She now responds: "Sorry, I can't do that for you" instead of opening the garage door like Siri has in the past.

**Comment by DMBlakeley** [comment]
Have you checked the name for your Garage Door in HomeKit? v2 of the MyQ2 app renamed “MyQ2 Garage Door Opener” by default. You can rename in HomeKit to “Garage Door” or your desired name for Siri to use.

**Comment by hjdhjd** [comment]
Thanks @DMBlakeley. It's a good push to shift the default name in a future release.

**Comment by MaverickC2** [comment]
@hjdhjd @DMBlakeley - Already renamed prior to reporting. My name is "Garage Door #1".

**Comment by DMBlakeley** [comment]
I believe that this is a Siri/HomeKit issue. My door is named “Garage Door”. When I ask “Hey Siri, is the Garage Door open” she replies accordingly with “Yes, the garage door is open”. When I change the name to “Garage Door 1” or “Garage Door #1” she responds that this request is not supported. May want to try “Main Garage Door”.

**Comment by MaverickC2** [comment]
@DMBlakeley - looks like you are on to something. I removed the "#1" and it now works. Weird thing is this just started happening. No iOS updates to the phone. Wonder what changed.

**Comment by DMBlakeley** [comment]
@MaverickC2 - there are certainly some inconsistencies in Siri and HomeKit!

Within HomeKit there are "rooms" and "accessories". I have my garage door opener in room "Garage" and named "Garage Door". Interestingly when you go to the room "Garage" in HomeKit the door is just named "Door". So possibly when I ask the question “Hey Siri, is the Garage Door open”, Siri is checking for "door" in room "garage".

**Comment by MaverickC2** [comment]
@DMBlakeley - I use it the same way.

**Comment by hjdhjd** [comment]
Closing this one...if you see continued issues specific to this plugin, please open a new report. Siri support is a broader HomeKit thing, and not specific to this plugin per se. If things work correctly in the Home app, then they should work correctly via Siri. If they don't, there's not much I can do on the app side and homebridge (and this plugin) have no direct mechanism to deal with Siri. Thanks and good luck.
