### ISSUE TITLE
Takes 5 minutes to connect to myQ

### ISSUE THREAD

**Issue by maxbadrak** [hjdhjd/homebridge-myq2#89]
Running the plugin 2.1.2 under node 12, with current Homebridge, on Windows. Looking at the logs, it takes 5 minutes from "initializing" to "successfully connected". 
`
[7/14/2020, 4:16:58 PM] [myQ] Initializing myQ platform...
[7/14/2020, 4:21:58 PM] [myQ] Successfully connected to the myQ API.
`
It looks like this makes the garage door unusable -- the commands don't come through. :( Any ideas how to troubleshoot this? 
Possibly related problem -- when I upgraded the plugin past 2.1 (I think), it started crashing because `node-fetch` module was missing. I worked around that by `npm i -g node-fetch`, but could this cause the weirdness?

**Comment by hjdhjd** [comment]
It’s a bit odd that installing the plugin didn’t install all it’s dependencies, including node-fetch. Can you elaborate on the specifics of your setup? What version of homebridge? And of homebridge-myq2? How’re you installing updates?

Thanks!

**Comment by maxbadrak** [comment]
Homebridge is 1.1.1, and homebridge-myq2 is 2.1.2. I install updates via 'npm i -g homebridge-myq2'
`
C:\Users\Administrator\.homebridge>npm list -g homebridge
C:\Users\Administrator\AppData\Roaming\npm
-- homebridge@1.1.1

C:\Users\Administrator\.homebridge>npm list -g homebridge-myq2
C:\Users\Administrator\AppData\Roaming\npm
-- homebridge-myq2@2.1.2
`

**Comment by hjdhjd** [comment]
Can you uninstall the plugin and reinstall cleanly and see if you still see an issue?

Are there any other log entries?

Thanks.

**Comment by maxbadrak** [comment]
Upgraded Node from 12 to 14.5, uninstalled node-fetch and homebridge-myq2, and then installed homebridge-myq2. This brought node-fetch correctly, and homebridge-myq2 now starts without errors. The apparent 5 minute delay is still there. Could it be because my `longPoll` is set to 300?

**Comment by hjdhjd** [comment]
Yep...that would be a problem. :smile: You’ve told the plugin to check once every five minutes...and it does!

**Comment by maxbadrak** [comment]
Shouldn't it check right away on startup though? I think earlier versions did that... (I am pretty sure it's not a false memory 😂 )

**Comment by hjdhjd** [comment]
It does immediately on initialization, but then goes to the longPoll interval. Why do you have such a long time interval configured? I’m curious.

**Comment by maxbadrak** [comment]
I thought 300 was the default "reasonable" value, so as to not overburden myQ servers. 🧐  Most likely I have it since the time I was trying other myQ/chamberlain plugins.

It looks like there might be a bug in the plugin -- when I start homebridge, the garage door is listed as "no response" for the first 5 minutes, which makes sense, since plugin only logs the door specifics after "successfully connected" message which happens 5 minutes after startup. When `longPoll` is set to 15 seconds  this is moot, because the delay is not noticeable. 😊

**Comment by hjdhjd** [comment]
The default values that are preconfigured are more than reasonable for almost everyone. Modify them to your liking, but from multiple years of experience, I can tell you that they’re pretty decent. :smile:

No response is the right answer until the garage door opener is polled...it’s not a bug, it’s behaving as designed.

I’ll take a look into polling once at initial startup, I appreciate you pointing out this edge case and it’ll be addressed in a future update. I’d suggest sticking with the defaults unless you have a good reason not to, however. Closing this one out.


Thanks!
