### ISSUE TITLE
Status reflected in Home App on macOS or iOS

### ISSUE THREAD

**Issue by jehrler** [hjdhjd/homebridge-myq2#9]
Wonderful plugin!

My only confusion is that I have the toggle switch to "Include in Status" but the summary on both the macOS and iOS versions of Home do not list garage door open/close in the status summary.
<img width="1020" alt="Screen Shot 2019-12-08 at 10 14 39 AM" src="https://user-images.githubusercontent.com/52459114/70392261-c1341100-19a3-11ea-8ae6-f82245b1cac5.png">
<img width="415" alt="Screen Shot 2019-12-08 at 10 15 34 AM" src="https://user-images.githubusercontent.com/52459114/70392262-c42f0180-19a3-11ea-98f3-0420ee1ede7e.png">
<img width="421" alt="Screen Shot 2019-12-08 at 10 15 49 AM" src="https://user-images.githubusercontent.com/52459114/70392264-c5f8c500-19a3-11ea-81e9-e7b7e7b837be.png">
In addition and probably relatedly, if I click on details under the status items, the new window does not list the garage door as one of the Status Details items.   
<img width="430" alt="Screen Shot 2019-12-08 at 10 14 52 AM" src="https://user-images.githubusercontent.com/52459114/70392260-bda08a00-19a3-11ea-9331-f4f8a78294b2.png">

**Comment by jehrler** [comment]
OK, I see that the status is only reflected when the door is open, not when it is closed.  Any chance to have the status, regardless of open/closed, in summary?  Or is this an Apple limitation?  Would be nice to tell at a glance where the garage door is at.

**Comment by hjdhjd** [comment]
I'm afraid this is an Apple-ism. Your best bet would be to add this to your Favorites so it's always on the main screen and it will show you whether it's open or closed. Thanks!
