### ISSUE TITLE
Plugin throwing 400 bad request errors, no longer working.

### ISSUE THREAD

**Issue by tiny-e** [hjdhjd/homebridge-myq2#90]
This repeats over and over in my log:
[7/15/2020, 8:59:51 AM] [MYQ2] myQ API error: 400 Bad Request
[7/15/2020, 8:59:51 AM] [MYQ2] myQ API error: unable to authenticate. Will retry later.

Plugin Version: homebridge-myq2 v2.1.2
Homebridge Version:  Version 1.1.1
Ubuntu Bionic Beaver (18.04.4 LTS)
NodeJS version:  v11.15.0
Npm Version:  v6.14.6

Not sure what's going on / how to troubleshoot further.

**Comment by xuanqian** [comment]
I am getting this over and over since this morning. Checked with my username and password and they are good with myQ.

[7/15/2020, 7:54:58 AM] [MyQ Homebridge] Invalid username or password given. Check your login and password.
[7/15/2020, 7:54:58 AM] [MyQ Homebridge] myQ API error: unable to refresh. Will retry later.

**Comment by dxdc** [comment]
me too @hjdhjd . Strange thing is, restarting hb fixes it. Maybe we need a trigger to refresh security token on these kinds of messages?

**Comment by hjdhjd** [comment]
I'm seeing similar. I'll push an update out soonish. Thanks.

**Comment by whreams** [comment]
Only been running the latest version for 24hrs, but all functions normally for me - including Siri commands. Strange others see different.

**Comment by tiny-e** [comment]
> me too @hjdhjd . Strange thing is, restarting hb fixes it. Maybe we need a trigger to refresh security token on these kinds of messages?

Restarting didn't help in my case.   Official myQ app is working fine,  however.

**Comment by hjdhjd** [comment]
Restart homebridge and all should be right with the world. I'm currently working on this one...thanks.

**Comment by xuanqian** [comment]
Restart homebridge fixed the problem. Thanks for the advise!

**Comment by tiny-e** [comment]
I'm still getting the same error:

> [7/15/2020, 3:50:24 PM] [MYQ2] myQ API error: 400 Bad Request
[7/15/2020, 3:50:24 PM] [MYQ2] myQ API error: unable to authenticate. Will retry later.

>

**Comment by hjdhjd** [comment]
The error you're getting isn't bad in and of itself. HTTP API errors happen with myQ. They just do. However, we don't seem to be recovering gracefully from them in some cases.

I've encountered it myself. I'm testing an update that hopefully addresses this. In the meantime, a reboot will fix it, though you may see these errors from time to time, they should be largely innocuous.

**Comment by banjohb** [comment]
> I'm still getting the same error:
> 
> 
> 
> > [7/15/2020, 3:50:24 PM] [MYQ2] myQ API error: 400 Bad Request
> 
> [7/15/2020, 3:50:24 PM] [MYQ2] myQ API error: unable to authenticate. Will retry later.
> 
> 
> 
> > 

Same error here. Restart don't fix the problem!

**Comment by hjdhjd** [comment]
Just published v2.1.3...give it a try.

**Comment by hjdhjd** [comment]
Closing this one. Open a new report if you see a bug. Thanks!

**Comment by tiny-e** [comment]
> Closing this one. Open a new report if you see a bug. Thanks!

Strangely, the plugin is working now.. and I have _not_ updated to the latest version... weird.   Thanks very much for the quick support!

**Comment by hjdhjd** [comment]
It's the myQ API that's flaky at times on the myQ end. Server availability on their end isn't always great and this plugin will shine a spotlight on those issues, and do so loudly as you've seen. :smile: We try to recover gracefully and retry at reasonable intervals until we can reestablish a connection. I'm working to streamline logging so it's not quite so alarming to people what's going on behind the scenes. Thanks!

**Comment by themick4u** [comment]
myQ] myQ API: Error: 400 Bad Request

**Comment by jbro1999** [comment]
Same here.  

[18/12/2020, 11:03:01] [myQ] myQ API: Error: 400 Bad Request
[18/12/2020, 11:03:01] [myQ] myQ API:  Unable to authenticate. Will retry later.

**Comment by mattob95** [comment]
Same issue here

**Comment by hjdhjd** [comment]
Well aware. https://github.com/hjdhjd/homebridge-myq/issues/226#issuecomment-755460907
