### ISSUE TITLE
Possibility to make motion sensor available?

### ISSUE THREAD

**Issue by jalustig** [hjdhjd/homebridge-myq2#91]
My LiftMaster automatically turns on its lights when it detects motion. Is there a way to make this available via HomeBridge so that we could have essentially a built in motion sensor?

**Comment by hjdhjd** [comment]
Short answer is: unlikely. If the myQ API exposes it, I can do something with it...but I haven't seen anything in the API that seems usable that can show motion sensor status. You can take a look for yourself by turning on debugging (but be warned, a lot of data will be logged). Look for the JSONs that show the myQ devices that get detected in status refreshes. If there's a field or entry for your motion sensors and their status, post it here and I'll take a look.

Looking at my own devices, there isn't a way to do this currently that I am aware of. Thanks!

**Comment by hjdhjd** [comment]
Bump on this one - if you have the JSON details above, I can look into supporting this in the future. Otherwise, I'll close this one due to inactivity. Thanks!

**Comment by jalustig** [comment]
I’ve looked at the JSON and I don’t believe that the device (or at least my version) makes the motion sensor data available. 

It seems actually that the motion sensor is on the wall mounted unit (which also incidentally has the button to turn on/off the light), not the actual garage door opener.

**Comment by hjdhjd** [comment]
Thanks for the followup. That's unfortunate. I hope in the future there's a bit more sophisticated support for things like that from myQ but time will tell. Closing this one out.
