### ISSUE TITLE
Non-Responsive

### ISSUE THREAD

**Issue by shanepinnell** [hjdhjd/homebridge-myq2#96]
Recently my garage door is not responsive. From the logs:

[7/21/2020, 12:12:02] [Garage] Invalid username or password given. Check your login and password.
[7/21/2020, 12:12:02] [Garage] myQ API error: unable to refresh. Will retry later.

**Comment by shanepinnell** [comment]
Username & Password are verified correct.

**Comment by whreams** [comment]
Maybe at this point we need to note the make/model of our opener?  Hard to see rhyme or reason to some of the errors.  Some see them, while other’s don’t.  Strange...

**Comment by shanepinnell** [comment]
LiftMaster 8500W

**Comment by shanepinnell** [comment]
Well, it looks like deleting and re-adding fixed the problem.
